export const menuItems = {
    items: [
        {
            label: 'My records (0)',
            value: '/approval/ALL',
            icon: 'home',
            status: 'ALL',
            sqlView: 'odg5FpAc79x',
            count: 0,
        },
        {
            label: 'Records for revision (0)',
            value: '/approval/Resend',
            icon: 'error_outline',
            status: 'Resend',
            sqlView: 'xFyCgPnxGHg',
            count: 0,
        },
        {
            label: 'Rejected records (0)',
            value: '/approval/Rejected',
            icon: 'highlight_off',
            status: 'Rejected',
            sqlView: 'UUTmMThacVx',
            count: 0,
        },
        {
            label: 'Accepted records (0)',
            value: '/approval/Approved',
            icon: 'check_circle_outline',
            status: 'Approved',
            sqlView: 'FHBxLVMynGb',
            count: 0,
        },
        {
            label: 'Records for validation (0)',
            value: '/approval/Validate',
            icon: 'help_outline',
            status: 'Validate',
            sqlView: 'Xraki4mz5B8',
            count: 0,
        },
    ],
    userOnly: true,
}
