export const menuItems = {
    items: [
        {
            label: 'My records (0)',
            value: '/approval/ALL',
            icon: 'home',
            status: 'ALL',
            countView: 'odg5FpAc79x',
            tableView: 'gPZgVJOeHk4',
            count: 0,
        },
        {
            label: 'Records for revision (0)',
            value: '/approval/Resend',
            icon: 'error_outline',
            status: 'Resend',
            countView: 'xFyCgPnxGHg',
            tableView: 'n5VaREaQ7aa',
            count: 0,
        },
        {
            label: 'Rejected records (0)',
            value: '/approval/Rejected',
            icon: 'highlight_off',
            status: 'Rejected',
            countView: 'UUTmMThacVx',
            tableView: 'F5n8ZowsJB5',
            count: 0,
        },
        {
            label: 'Accepted records (0)',
            value: '/approval/Approved',
            icon: 'check_circle_outline',
            status: 'Approved',
            countView: 'FHBxLVMynGb',
            tableView: 'NpHoZ0PCGNY',
            count: 0,
        },
        {
            label: 'Records for validation (0)',
            value: '/approval/Validate',
            icon: 'help_outline',
            status: 'Validate',
            countView: 'Xraki4mz5B8',
            tableView: 'k4Or0pHTmPN',
            count: 0,
        },
    ],
    userOnly: true,
}
