export const trackedEntityAttributes = [
    {
        name: 'Age / DOB',
        id: 'DfXY7WHFzyc',
        displayName: 'Age / DOB',
        valueType: 'TEXT',
        unique: false,
        optionSetValue: false,
    },
    {
        name: 'City / Town / Village',
        id: 'dTv0U5EeJhw',
        displayName: 'City / Town / Village',
        valueType: 'TEXT',
        unique: false,
        optionSetValue: false,
    },
    {
        name: 'District',
        id: 'SOVNMvY8TOf',
        displayName: 'District',
        valueType: 'TEXT',
        unique: false,
        optionSetValue: true,
        optionSet: {
            id: 'hRHti3LG2H9',
        },
    },
    {
        name: 'Gender',
        id: 'VXRRpqAdrdK',
        displayName: 'Gender',
        valueType: 'TEXT',
        unique: false,
        optionSetValue: true,
        optionSet: {
            id: 'zKaC5j0HCxc',
        },
    },
    {
        name: 'Location type',
        id: 'Wo36m1aczPN',
        displayName: 'Location type',
        valueType: 'TEXT',
        unique: false,
        optionSetValue: true,
        optionSet: {
            id: 'eorHmh6WMYF',
        },
    },
    {
        name: 'Registration number',
        id: 'nFrlz82c6jS',
        displayName: 'Registration number',
        valueType: 'TEXT',
        unique: false,
        optionSetValue: false,
    },
    {
        name: 'State',
        id: 'ZgUp0jFVxdY',
        displayName: 'State',
        valueType: 'TEXT',
        unique: false,
        optionSetValue: true,
        optionSet: {
            id: 'Qmw80K0ysKI',
        },
    },
]
