// METADATA
export const METADATA_RECEIVED = 'METADATA_RECEIVED'
export const METADATA_ERRORED = 'METADATA_ERRORED'

// ORG UNIT
export const ORG_UNIT_SELECTED = 'ORG_UNIT_SELECTED'

// ALERT
export const ADD_ALERT = 'ADD_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'

// DATA
export const RESET_DATA = 'RESET_DATA'
export const EXISTING_DATA_RECEIVED = 'EXISTING_DATA_RECEIVED'
export const EXISTING_DATA_ERRORED = 'EXISTING_DATA_ERRORED'
export const DISABLE_BUTTONS = 'DISABLE_BUTTONS'
export const RESET_PANEL_EVENT = 'RESET_PANEL_EVENT'
export const SET_INCOMPLETED = 'SET_INCOMPLETED'
export const SET_DELETE_PROMPT = 'SET_DELETE_PROMPT'

// ENTITY
export const SET_ENTITY = 'SET_ENTITY'
export const SET_ENTITY_VALUE = 'SET_ENTITY_VALUE'
export const SET_UNIQUE = 'SET_UNIQUE'
export const SET_ENTITY_MODAL_AND_UNIQUES = 'SET_ENTITY_MODAL_AND_UNIQUES'
export const SET_EDITING = 'SET_EDITING'

// PANEL
export const SET_PANEL = 'SET_PANEL'
export const SET_PANEL_VALUE = 'SET_PANEL_VALUE'
export const RESET_PANEL = 'RESET_PANEL'

// EVENT
export const SET_ENTITY_AND_ORG_UNIT = 'SET_ENTITY_AND_ORG_UNIT'
export const SET_EVENT_VALUE = 'SET_EVENT_VALUE'
export const SET_EVENT_AND_ENTITY = 'SET_EVENT_AND_ENTITY'
export const SET_EVENT_VALUES_AND_PROGRAMSTAGE =
    'SET_EVENT_VALUES_AND_PROGRAMSTAGE'
export const DUPLICACY = 'DUPLICACY'
