// METADATA
export const METADATA_RECEIVED = 'METADATA_RECEIVED'
export const METADATA_ERRORED = 'METADATA_ERRORED'

// ORG UNIT
export const ORG_UNIT_SELECTED = 'ORG_UNIT_SELECTED'

// DATA
export const EXISTING_DATA_RECEIVED = 'EXISTING_DATA_RECEIVED'
export const EXISTING_DATA_ERRORED = 'EXISTING_DATA_ERRORED'
export const DISABLE_BUTTONS = 'DISABLE_BUTTONS'
export const RESET_PANEL_EVENT = 'RESET_PANEL_EVENT'

// ENTITY
export const SET_ENTITY = 'SET_ENTITY'
export const UPDATE_ENTITY = 'UPDATE_ENTITY'
export const SET_UNIQUE = 'SET_UNIQUE'
export const SET_ENTITY_MODAL_AND_UNIQUES = 'SET_ENTITY_MODAL_AND_UNIQUES'
export const SET_EDITING = 'SET_EDITING'
export const RESET_ENTITY = 'RESET_ENTITY'

// PANEL
export const SET_PANEL = 'SET_PANEL'
export const SET_PANEL_VALUE = 'SET_PANEL_VALUE'
export const RESET_PANEL = 'RESET_PANEL'

// Record
export const NEW_RECORD = 'NEW_RECORD'
export const EXISTING_RECORD = 'EXISTING_RECORD'
export const EDIT = 'EDIT'
export const DISABLE_BUTTON = 'DISABLE_BUTTON'
export const EVENT_VALID = 'EVENT_VALID'
export const DELETE_CLICKED = 'DELETE_CLICKED'
export const DELETE_CONFIRMED = 'DELETE_CONFIRMED'
export const SET_LOADING = 'SET_LOADING'
export const SET_CODE = 'SET_CODE'
export const SET_DUPLICATE = 'SET_DUPLICATE'
