export const menuItems = {
    items: [
        {
            label: 'My records (0)',
            value: '/approval/ALL',
            icon: 'home',
            status: 'ALL',
            countView: 'odg5FpAc79x',
            count: 0,
        },
        {
            label: 'Records for revision (0)',
            value: '/approval/Resend',
            icon: 'error_outline',
            status: 'Resend',
            countView: 'xFyCgPnxGHg',
            count: 0,
        },
        {
            label: 'Rejected records (0)',
            value: '/approval/Rejected',
            icon: 'highlight_off',
            status: 'Rejected',
            countView: 'UUTmMThacVx',
            count: 0,
        },
        {
            label: 'Accepted records (0)',
            value: '/approval/Approved',
            icon: 'check_circle_outline',
            status: 'Approved',
            countView: 'FHBxLVMynGb',
            count: 0,
        },
        {
            label: 'Records for validation (0)',
            value: '/approval/Validate',
            icon: 'help_outline',
            status: 'Validate',
            countView: 'Xraki4mz5B8',
            count: 0,
        },
        {
            label: 'Incomplete records (0)',
            value: '/approval/Incomplete',
            icon: 'pause_circle_outline',
            status: 'Incomplete',
            countView: 'NmiQ8wvL2fD',
            count: 0,
        },
    ],
    userOnly: true,
}
