export const optionsObjectified = {
    XBmAFYq00eF: { label: '16s rRNA Sequencing', value: '16s rRNA Sequencing' },
    ub7jLskpFn3: { label: 'Abdominal fluid', value: 'Abdominal fluid' },
    LS8uIpY01Yh: { label: 'Abhishegapakkam PHC', value: 'Abhishegapakkam PHC' },
    IiMKpH4aWHG: { label: 'Abscess aspirate', value: 'Abscess aspirate' },
    q41sZU7I6m7: {
        label: 'Accident and Emergency',
        value: 'Accident and Emergency',
    },
    kdDWqTyz7JH: { label: 'Acinetobacter', value: 'Acinetobacter' },
    F9jqfeec3a9: { label: 'Acinetobacter baumannii', value: 'ABA' },
    Y2UsLLW9wVU: { label: 'Acinetobacter calcoaceticus', value: 'ACA' },
    yMDpiDBMScq: { label: 'Acinetobacter lwoffii', value: 'ALW' },
    IpT9TCXc8It: { label: 'Acinetobacter spp.', value: 'AC-' },
    f2FpjjAEvjs: { label: 'Actobacterium sp.', value: 'ACE' },
    hsbpoFyZwtt: { label: 'adeninivorans', value: 'adeninivorans' },
    jRAE2iFVK6r: { label: 'Adilabad', value: 'Adilabad' },
    dvMFh8PuV2H: {
        label: 'Advance Trauma Centre',
        value: 'Advance Trauma Centre',
    },
    QWkfDYGuBKk: { label: 'aerogenes', value: 'aerogenes' },
    HvaI1BMziGP: { label: 'Aeromonas', value: 'Aeromonas' },
    bMT2HPKioZ5: { label: 'Aeromonas spp.', value: 'AER' },
    Hg2Vs1aGUuo: { label: 'aeruginosa', value: 'aeruginosa' },
    atIdWxPjdBm: { label: 'AFA', value: 'AFA' },
    RisgnQa2Khp: { label: 'agalactiae', value: 'agalactiae' },
    lhx7MgfccKh: { label: 'Agar', value: 'Agar' },
    DlpjcHf1ox6: { label: 'Agra', value: 'Agra' },
    RDDwitM03FG: { label: 'Ahmedabad', value: 'Ahmedabad' },
    Vc4UZyoRKgn: { label: 'Ahmednagar', value: 'Ahmednagar' },
    hvXtj08Nfae: { label: 'Aizawl', value: 'Aizawl' },
    YZRXZgMagH8: { label: 'Ajmer', value: 'Ajmer' },
    O9Gt6iUbJP3: { label: 'Akola', value: 'Akola' },
    rJbJ6kG2ZS5: { label: 'Alappuzha', value: 'Alappuzha' },
    B4qg7BOtIDh: { label: 'albicans', value: 'albicans' },
    dXaUBUraXyg: { label: 'Aligarh', value: 'Aligarh' },
    fun8DH0Q8sm: { label: 'Alipurduar', value: 'Alipurduar' },
    kX3rgtqVOgW: { label: 'Alirajpur', value: 'Alirajpur' },
    yUEHHvmCffr: { label: 'Alive', value: 'Alive' },
    VOERo9xfEkp: { label: 'Allahabad', value: 'Allahabad' },
    KH82SdsyrAz: { label: 'Almora', value: 'Almora' },
    XCYjXEpFW6l: { label: 'alvei', value: 'alvei' },
    ZJEV3BTIbaV: { label: 'Alwar', value: 'Alwar' },
    a4wFi9h3X1l: { label: 'Ambala', value: 'Ambala' },
    X4RE2De8KSw: { label: 'Ambedkar Nagar', value: 'Ambedkar Nagar' },
    LI36EejUiM1: {
        label: 'Amethi (Chhatrapati Shahuji Maharaj Nagar)',
        value: 'Amethi (Chhatrapati Shahuji Maharaj Nagar)',
    },
    cOnDNuaBBW8: { label: 'Amravati', value: 'Amravati' },
    p90bmLDH3Hp: { label: 'Amreli district', value: 'Amreli district' },
    RosNeZu2mqj: { label: 'Amritsar', value: 'Amritsar' },
    v1M0LuqT4Bd: { label: 'Anaesthesia', value: 'Anaesthesia' },
    Zy5EoxdQlps: {
        label: 'Anaesthesia and Intensive Care',
        value: 'Anaesthesia and Intensive Care',
    },
    DAQDHlZt7o9: {
        label: 'Anaesthesiology & Critical Care',
        value: 'Anaesthesiology & Critical Care',
    },
    o5Y1suZK3fb: { label: 'Anand', value: 'Anand' },
    Y98XGFzX1O1: { label: 'Anantapur', value: 'Anantapur' },
    g0E0EKsYWc6: { label: 'Anantnag', value: 'Anantnag' },
    h0KdL1O75wU: { label: 'Anatomy', value: 'Anatomy' },
    RrckZ4xfZjn: { label: 'Andaman and Nicobar', value: 'Andaman and Nicobar' },
    mHE0ofM6vwQ: { label: 'Andhra Pradesh', value: 'Andhra Pradesh' },
    wE27TvXs8kY: { label: 'Angul', value: 'Angul' },
    bxEp8BLN0sh: { label: 'Animal', value: 'Animal' },
    pE8NETWHQ6p: { label: 'Anjaw', value: 'Anjaw' },
    LBotf9noqNx: { label: 'anomalus', value: 'anomalus' },
    EKlDw2i5GHB: { label: 'Anuppur', value: 'Anuppur' },
    tZJGCnxuzrO: { label: 'aphidis', value: 'aphidis' },
    XVuahYU5oNk: { label: 'Approved', value: 'Approved' },
    c1pdDFRwNUM: { label: 'Araria', value: 'Araria' },
    HL1DPQDgsQB: { label: 'Aravalli', value: 'Aravalli' },
    rIqRfZMESml: { label: 'Ariyalur', value: 'Ariyalur' },
    n9yrLRECkMz: { label: 'Ariyur PHC', value: 'Ariyur PHC' },
    NLsQ51RBZji: { label: 'Arizona', value: 'Arizona' },
    kh45JkHsyr6: { label: 'Arizona spp.', value: 'ARI' },
    BhOJ1jJXtMo: { label: 'Arunachal Pradesh', value: 'Arunachal Pradesh' },
    mhYDeb9I49F: { label: 'Arwal', value: 'Arwal' },
    xDm74CovAeB: { label: 'asahii', value: 'asahii' },
    Mn28wZZ0RvK: { label: 'Ashok Nagar', value: 'Ashok Nagar' },
    BSShLJpQEOn: { label: 'Aspergillus', value: 'Aspergillus' },
    DOcjxre44jZ: { label: 'Aspergillus flavus', value: 'AFL' },
    tnIzbvsog2V: { label: 'Aspergillus fumigatus', value: 'AFU' },
    vV5se5mOEhE: { label: 'Aspergillus nidulans', value: 'AND' },
    jFTslqHMqc8: { label: 'Aspergillus niger', value: 'ANI' },
    FE8y7i2uC2w: { label: 'Aspergillus terreus', value: 'ATE' },
    x6mXAr0ozeK: { label: 'Aspergillus versicolor', value: 'AVL' },
    J2vmycKpqqq: { label: 'Assam', value: 'Assam' },
    gq1cwl9D4bP: { label: 'Auraiya', value: 'Auraiya' },
    zRBe7WEjp4Z: { label: 'Aurangabad-B', value: 'Aurangabad-B' },
    G1SapdaOzma: { label: 'Aurangabad - MH', value: 'Aurangabad-M' },
    zd19wjDZI4b: { label: 'aureus', value: 'aureus' },
    y5Tu8ApYbAe: { label: 'auris', value: 'auris' },
    vpGd3EkxfFQ: { label: 'Azamgarh', value: 'Azamgarh' },
    QpouA30kYNZ: { label: 'Badgam', value: 'Badgam' },
    yvYP9efKlcQ: { label: 'Bagalkot', value: 'Bagalkot' },
    P3qEZPc14jN: { label: 'Bageshwar', value: 'Bageshwar' },
    QopfTh7JpWU: { label: 'Bagpat', value: 'Bagpat' },
    ESZaCgXyvBK: { label: 'Bahour PHC', value: 'Bahour PHC' },
    UwjUXBDexrD: { label: 'Bahraich', value: 'Bahraich' },
    kOS2W7l4pvA: { label: 'Baksa', value: 'Baksa' },
    eW3dBxuN5Sl: { label: 'BAL', value: 'BAL' },
    MF2VO1eAQGa: { label: 'Balaghat', value: 'Balaghat' },
    eV41hiNI9gN: { label: 'Balangir', value: 'Balangir' },
    HtPUDgcMH6Q: { label: 'Balasore', value: 'Balasore' },
    ADldFPm3tYe: { label: 'Ballia', value: 'Ballia' },
    L715eGLEPMS: { label: 'Balod', value: 'Balod' },
    Kxmjqe7abVM: { label: 'Baloda Bazar', value: 'Baloda Bazar' },
    lbPwUKgTeEZ: { label: 'Balrampur-C', value: 'Balrampur-C' },
    AyDMLWWOxYa: { label: 'Balrampur-UP', value: 'Balrampur-UP' },
    XRGN8zxHJJL: { label: 'Banaskantha', value: 'Banaskantha' },
    ro2vr1LzIgg: { label: 'Banda', value: 'Banda' },
    efchCc4UB1K: { label: 'Bandipora', value: 'Bandipora' },
    JgDoC4PZzNL: { label: 'Bandipur', value: 'Bandipur' },
    JHPGl8TWSby: { label: 'Bangalore', value: 'Bangalore' },
    KASjwjN1wm8: { label: 'Banka', value: 'Banka' },
    jjb8AGWRsUB: { label: 'Bankura', value: 'Bankura' },
    xqFnT4ErQnv: { label: 'Banswara', value: 'Banswara' },
    puq2o911C4i: { label: 'Barabanki', value: 'Barabanki' },
    gi7y9MHGyIB: { label: 'Baramulla', value: 'Baramulla' },
    fieV48bdy9o: { label: 'Baran', value: 'Baran' },
    hXeWHxbcltQ: { label: 'Bardhaman', value: 'Bardhaman' },
    kcb0UHYhTnl: { label: 'Bareilly', value: 'Bareilly' },
    hUYoQ3afLXq: { label: 'Bargarh (Baragarh)', value: 'Bargarh (Baragarh)' },
    PtFvwcPNUl2: { label: 'Barmer', value: 'Barmer' },
    oXxLNjJWCW0: { label: 'Barnala', value: 'Barnala' },
    MRvU9Lp6GlD: { label: 'Barpeta', value: 'Barpeta' },
    zAuxCXxmnSo: { label: 'Barwani', value: 'Barwani' },
    m9svQclrzgJ: { label: 'Basirhat HD', value: 'Basirhat HD' },
    ylbg6u8k9CH: { label: 'Bastar', value: 'Bastar' },
    k2jmmagPwZV: { label: 'Basti', value: 'Basti' },
    me49tmTnQaa: { label: 'Bathinda', value: 'Bathinda' },
    Lss58CbYTGK: {
        label: 'baumanii-calcoaceticus complex',
        value: 'baumanii-calcoaceticus complex',
    },
    stiVi5WirYp: { label: 'baumannii', value: 'baumannii' },
    EMk8e9onukB: { label: 'Beed', value: 'Beed' },
    OwUZKe0gwkb: { label: 'Begusarai', value: 'Begusarai' },
    e62BTLuXBRR: { label: 'Belgaum', value: 'Belgaum' },
    MAi6We031qI: { label: 'Bellary', value: 'Bellary' },
    eaawG7VgSZz: { label: 'Bemetara', value: 'Bemetara' },
    SUHrB671yxo: { label: 'Betul', value: 'Betul' },
    McWPzSCLah2: { label: 'Bhadohi', value: 'Bhadohi' },
    uQAsaQ1j5bV: { label: 'Bhadrak', value: 'Bhadrak' },
    aXbJ4jdtHRO: { label: 'Bhagalpur', value: 'Bhagalpur' },
    PILvrxdP8d5: { label: 'Bhandara', value: 'Bhandara' },
    rRQSii3o7YA: { label: 'Bharatpur', value: 'Bharatpur' },
    eyZI1xvhR5w: { label: 'Bharuch', value: 'Bharuch' },
    TV7NAhZ1ABt: { label: 'Bhavnagar', value: 'Bhavnagar' },
    EcAdONYUKAZ: { label: 'Bhilwara', value: 'Bhilwara' },
    cVnAlJzCJSI: { label: 'Bhind', value: 'Bhind' },
    wx3L6qHkUS5: { label: 'Bhiwani', value: 'Bhiwani' },
    HmIZo6EcYFA: { label: 'Bhojpur', value: 'Bhojpur' },
    uC3uUg7Kr40: { label: 'Bhopal', value: 'Bhopal' },
    mwcQmXPeLum: { label: 'Bidar', value: 'Bidar' },
    AAhjoZpwM3C: { label: 'Bihar', value: 'Bihar' },
    m4BlIr4MT1O: { label: 'Bijapur', value: 'Bijapur' },
    UI1o6yvYT88: { label: 'Bijnor', value: 'Bijnor' },
    Bh7i1FiWWmd: { label: 'Bikaner', value: 'Bikaner' },
    cnKDQQjBM5j: { label: 'Bilaspur-C', value: 'Bilaspur-C' },
    iAxuFxrx9zr: { label: 'Bilaspur-HP', value: 'Bilaspur-HP' },
    YiTBM8y7suP: { label: 'Bile', value: 'Bile' },
    U504rDbnADI: { label: 'Biochemical test', value: 'Biochemical test' },
    ONfyFO7yJ38: { label: 'Biochemistry', value: 'Biochemistry' },
    HvK23NmJcwm: { label: 'Birbhum', value: 'Birbhum' },
    iGYdWctnMCx: { label: 'Bishnupur', value: 'Bishnupur' },
    dE2wIF6d1Yb: { label: 'Bishnupur HD', value: 'Bishnupur HD' },
    oJ202sHhhNl: { label: 'Blastobortrys', value: 'Blastobortrys' },
    JccsQmUqWN6: { label: 'Blastobortrys adeninivorans', value: 'BLA' },
    yMRiOGdZ30V: {
        label: 'Blood-central catheter',
        value: 'Blood-central catheter',
    },
    e7L19OfK4D1: { label: 'Blood-peripheral', value: 'Blood-peripheral' },
    CJe5c6tOIt6: { label: 'Bokaro', value: 'Bokaro' },
    Cn14HbfSrBp: { label: 'Bone', value: 'Bone' },
    hWUHWQEwx9h: { label: 'Bone Marrow', value: 'Bone Marrow' },
    Z3Rl1xZqUtf: {
        label: 'Bone Marrow Transplant',
        value: 'Bone Marrow Transplant',
    },
    ZBaiSzgkw45: { label: 'Bongaigaon', value: 'Bongaigaon' },
    diz9KBclicq: { label: 'Botad', value: 'Botad' },
    kuabzfICto5: { label: 'Boudh (Bauda)', value: 'Boudh (Bauda)' },
    yGm1tFzbz74: { label: 'boydii', value: 'boydii' },
    qsDsxsHKp14: { label: 'Brain abscess', value: 'Brain abscess' },
    d8UR4eWeqv7: { label: 'Breast Oncology', value: 'Breast Oncology' },
    sUDScE2o7F2: { label: 'Brevundimonas diminuta', value: 'PDI' },
    AEnj1of75H5: { label: 'BSAC', value: 'BSAC' },
    aeJJvMkVkle: { label: 'Budaun', value: 'Budaun' },
    bmOuJKIh1wf: { label: 'Bulandshahr', value: 'Bulandshahr' },
    mQa9msPQ3eF: { label: 'Buldhana', value: 'Buldhana' },
    G5EeuTlXt1U: { label: 'Bundi', value: 'Bundi' },
    DdVk8gBNmD4: { label: 'Burhanpur', value: 'Burhanpur' },
    pF9vwCBZPvE: { label: 'Burkholderia', value: 'Burkholderia' },
    YXhjWzJPNnz: { label: 'Burkholderia cepacia', value: 'PCE' },
    mNrG25AdD0Z: { label: 'Burn Unit', value: 'Burn Unit' },
    DiDaXC5DG4S: { label: 'Buxar', value: 'Buxar' },
    uXipjE3ypGY: { label: 'Cachar', value: 'Cachar' },
    IVdnF83v5y3: { label: 'calcoaceticus', value: 'calcoaceticus' },
    I1LE2vfz8gN: { label: 'Campylobacter', value: 'Campylobacter' },
    iw2QVg4x9RD: { label: 'Campylobacter jejuni', value: 'CAJ' },
    bxpm9edZ6hT: { label: 'Candida', value: 'Candida' },
    mcfNbhuKZi7: { label: 'Candida albicans', value: 'CAL' },
    M9hC6IDxXF8: { label: 'Candida auris', value: 'CAA' },
    L8Gk0OOkWwr: { label: 'Candida catenulata', value: 'CCT' },
    E5XP5OUlqV3: { label: 'Candida chiropterorum', value: 'CCP' },
    w6bqH8Ft2qw: { label: 'Candida famata', value: 'TCA' },
    jVCYSNPLY5I: { label: 'Candida glabrata', value: 'CGL' },
    T8sBYGOgg0o: { label: 'Candida guilliermondii', value: 'CGU' },
    G222cYSUU46: { label: 'Candida haemulonii', value: 'THA' },
    JD1SKiOqyPi: { label: 'Candida intermedia', value: 'CIN' },
    lGu8ZBoEScG: { label: 'Candida kefyr', value: 'CPS' },
    mHw7sAitACv: { label: 'Candida krusei', value: 'CKR' },
    dUX6GhA1g7h: { label: 'Candida lipolytica', value: 'CLP' },
    ajwJhNbiBsG: { label: 'Candida lusitaniae', value: 'CLU' },
    kGvura56zR3: { label: 'Candida nivariensis', value: 'CAN' },
    fcv8QBJxQWw: { label: 'Candida parapsilosis', value: 'CPA' },
    KnThY1N1XbG: { label: 'Candida pararugosa', value: 'CPR' },
    Zff0qDgmeRV: { label: 'Candida pelliculosa', value: 'CNP' },
    goOvX5hSGcL: { label: 'Candida rugosa', value: 'CRU' },
    toKRaRQBAdM: { label: 'Candida tropicalis', value: 'CTR' },
    ctakjY4Kdhh: { label: 'Candida utilis', value: 'CUT' },
    yHRwCPQkidp: { label: 'Candida vishwanathii', value: 'CAV' },
    dDUecuZntHl: { label: 'Cardiology', value: 'Cardiology' },
    jE35Ye7AfBK: {
        label: 'Cardio thoracic and Vascular Surgery',
        value: 'Cardio thoracic and Vascular Surgery',
    },
    JGipYcS7cLT: {
        label: 'Cardio thoracic surgery',
        value: 'Cardio thoracic surgery',
    },
    enFhvRVabvr: { label: 'catenulata', value: 'catenulata' },
    tfYsDdQRLNc: { label: 'Central Delhi', value: 'Central Delhi' },
    JZOfPWdxEho: {
        label: 'Central line catheter',
        value: 'Central line catheter',
    },
    wDtZylk4Pxn: { label: 'cepacia', value: 'cepacia' },
    WGpb3dD6F2w: { label: 'cepacia complex', value: 'cepacia complex' },
    lzX0TPIvQd6: { label: 'cerevisiae', value: 'cerevisiae' },
    Z5qbxBDXgs9: { label: 'Cervical Swab', value: 'Cervical Swab' },
    a7h6NxUBt0N: { label: 'Chamarajnagar', value: 'Chamarajnagar' },
    zZdRDmIv3IY: { label: 'Chamba', value: 'Chamba' },
    tohMuG4FgDs: { label: 'Chamoli', value: 'Chamoli' },
    MCeteenfLiQ: { label: 'Champawat', value: 'Champawat' },
    G8CYbS74dJJ: { label: 'Champhai', value: 'Champhai' },
    LsiBvAW2kq6: { label: 'Chandauli', value: 'Chandauli' },
    kDwlQJ3LEXp: { label: 'Chandel', value: 'Chandel' },
    OgkfCMoGKzu: { label: 'Chandigarh', value: 'Chandigarh' },
    JqRG2nE5Dfm: { label: 'Chandigarh', value: 'Chandigarh' },
    Ce2NYqSvBnw: { label: 'Chandrapur', value: 'Chandrapur' },
    yLqKw1pqpiY: { label: 'Changlang', value: 'Changlang' },
    V1q0rRzC0DE: { label: 'Chatra', value: 'Chatra' },
    Gxzp64AB4Bf: { label: 'Chennai', value: 'Chennai' },
    Xo7fLQvz6ky: { label: 'Chhatarpur', value: 'Chhatarpur' },
    xdxVSOznmpS: { label: 'Chhattisgarh', value: 'Chhattisgarh' },
    QIXfZYry2T8: { label: 'Chhindwara', value: 'Chhindwara' },
    q7JYAc92jX9: { label: 'Chhota Udaipur', value: 'Chhota Udaipur' },
    jURXfN3qyv9: { label: 'Chikkaballapur', value: 'Chikkaballapur' },
    iUecbGe92jK: { label: 'Chikkamagaluru', value: 'Chikkamagaluru' },
    N5urKJgXkQa: { label: 'Child health', value: 'Child health' },
    dvTjeId0Ujo: { label: 'Chirang', value: 'Chirang' },
    DX60IjKguTB: { label: 'chiropterorum', value: 'chiropterorum' },
    M7BgdHyMd7H: { label: 'Chitradurga', value: 'Chitradurga' },
    Enw5qOPt3P3: { label: 'Chitrakoot', value: 'Chitrakoot' },
    AU5zE8zmjxd: { label: 'Chittoor', value: 'Chittoor' },
    vUrkKeYbp3F: { label: 'Chittorgarh', value: 'Chittorgarh' },
    zEEqzxzKv7H: { label: 'cholerae', value: 'cholerae' },
    jRJrss64rUw: { label: 'Churachandpur', value: 'Churachandpur' },
    cn4fS5jmHgG: { label: 'churashimaensis', value: 'churashimaensis' },
    cYtJRG26ItD: { label: 'Churu', value: 'Churu' },
    ZTSHKvXPrXA: { label: 'Citrobacter', value: 'Citrobacter' },
    HPpVPDcYrXy: { label: 'Citrobacter freundii', value: 'CFR' },
    jpsNQTzTBmX: { label: 'Citrobacter freundii', value: 'CFR' },
    B0FTsRMR9FX: { label: 'Citrobacter koseri', value: 'CDI' },
    wLDwkvNEl9s: { label: 'Citrobacter koseri', value: 'CDI' },
    gWEZYPSLGZv: { label: 'Citrobacter spp.', value: 'CIT' },
    u4jfZ8N9ypq: { label: 'Citrobacter spp.', value: 'CIT' },
    RWmQGkwzhvb: { label: 'Clinical Immunology', value: 'Clinical Immunology' },
    RVRJWIdMLZR: { label: 'Clinical Nutrition', value: 'Clinical Nutrition' },
    e4j6OdWHdiN: {
        label: 'Clinical Pharmacology',
        value: 'Clinical Pharmacology',
    },
    XdAtq9r5COY: { label: 'cloacae', value: 'cloacae' },
    viYsctGLfb8: { label: 'Clostridium', value: 'Clostridium' },
    kQOZZumBwGZ: { label: 'Clostridium difficile', value: 'CDF' },
    M47qwvBaC9D: { label: 'Clostridium novyi', value: 'CNO' },
    OHY8HPtLqEs: { label: 'CLSI', value: 'CLSI' },
    saAfikoPpBs: { label: 'Coimbatore', value: 'Coimbatore' },
    g5IZlI18Vhq: { label: 'coli', value: 'coli' },
    CceIWWNlmbw: { label: 'College of Nursing', value: 'College of Nursing' },
    a7JprlXnw5Z: {
        label: 'Communicable Disease Ward',
        value: 'Communicable Disease Ward',
    },
    B71gOG0A9YV: {
        label: 'Community acquired infection',
        value: 'Community acquired',
    },
    OzQ3E2BrLWQ: {
        label: 'Community health and Development',
        value: 'Community health and Development',
    },
    jSepAVz4wgj: { label: 'Confirmed', value: 'Confirmed' },
    j72DL0gQHtl: { label: 'Contaminated', value: 'Contaminated' },
    hyuoOYXqmNa: { label: 'Cooch Behar', value: 'Cooch Behar' },
    KFr1GGh7V59: { label: 'Corynebacterium sp. (diphtheroids)', value: 'CDP' },
    os9PojuDdPI: { label: 'Cryptococcus', value: 'Cryptococcus' },
    yB8ujSS1RNy: { label: 'Cryptococcus neoformans', value: 'CNE' },
    tbpkQIAzu5T: { label: 'Cryptococcus neoformans var gattii', value: 'CGT' },
    yvlB3e8bGTT: { label: 'Cryptococcus neoformans var grubii', value: 'CNG' },
    Od8CqpnnMnM: { label: 'CSF', value: 'CSF' },
    ypnqamNCgX9: { label: 'Cuddalore', value: 'Cuddalore' },
    SsEre1WGC6a: { label: 'Cuttack', value: 'Cuttack' },
    nKDjuJVFA9Y: {
        label: 'Dadra and Nagar Haveli',
        value: 'Dadra and Nagar Haveli',
    },
    oYN4h8JoKSs: {
        label: 'Dadra and Nagar Haveli',
        value: 'Dadra and Nagar Haveli',
    },
    ArbzRAOpWoc: { label: 'Dahod', value: 'Dahod' },
    zOmP8823cWr: { label: 'Dakshina Kannada', value: 'Dakshina Kannada' },
    xSAFvbJmsJo: { label: 'Dakshin Dinajpur', value: 'Dakshin Dinajpur' },
    YMx494BH0qm: { label: 'Daman', value: 'Daman' },
    GFlIjPtDVdi: { label: 'Daman and Diu', value: 'Daman and Diu' },
    aQ0NBQYYYUS: { label: 'Damoh', value: 'Damoh' },
    i1Pj2QsuGwg: { label: 'Dang', value: 'Dang' },
    LFO8woxTzCU: { label: 'Dantewada', value: 'Dantewada' },
    NIGVRmQeicC: { label: 'Darbhanga', value: 'Darbhanga' },
    sgfPsir1xVD: { label: 'Darjeeling', value: 'Darjeeling' },
    EejyHjh8Js0: { label: 'Darrang', value: 'Darrang' },
    xhdS9MTZ9nm: { label: 'Datia', value: 'Datia' },
    lb9QWYzo628: { label: 'Dausa', value: 'Dausa' },
    t16rCstfmIE: { label: 'Davanagere', value: 'Davanagere' },
    kRnPgHYAgz3: { label: 'Dead', value: 'Dead' },
    fCj3hCKXepT: { label: 'Debagarh (Deogarh)', value: 'Debagarh (Deogarh)' },
    ULmRPU6lciM: { label: 'Debaromyces', value: 'Debaromyces' },
    rE56GSc9yBI: { label: 'Debaromyces hansenii', value: 'DBH' },
    XeQWraC3057: { label: 'Deep Biopsy', value: 'Deep Biopsy' },
    OUmX7Lw6Nsq: { label: 'Deep Tissue', value: 'Deep Tissue' },
    I7tPzPfiFWl: { label: 'Dehradun', value: 'Dehradun' },
    F1r9DXZPaCZ: { label: 'Delhi', value: 'Delhi' },
    vJbeSaeG6RH: {
        label: 'Dental and Oral surgery',
        value: 'Dental and Oral surgery',
    },
    HpWgAAaE4vG: { label: 'Deoghar', value: 'Deoghar' },
    Hh0oeNSSyYl: { label: 'Deoria', value: 'Deoria' },
    Dcqx2ReBGNL: { label: 'Dermatology', value: 'Dermatology' },
    cdbVMl7EpWV: { label: 'Dermatology and STD', value: 'Dermatology and STD' },
    f2qcNgToTVV: { label: 'Devbhoomi Dwarka', value: 'Devbhoomi Dwarka' },
    rTrAoIKMzkN: { label: 'Dewas', value: 'Dewas' },
    bGNQCdZyrJi: { label: 'Dhalai', value: 'Dhalai' },
    d5I6QI0nLNH: { label: 'Dhamtari', value: 'Dhamtari' },
    Jg2yxM81uRD: { label: 'Dhanbad', value: 'Dhanbad' },
    zsnmbvQlkxf: { label: 'Dhar', value: 'Dhar' },
    jZDrEdD4Wsm: { label: 'Dharmapuri', value: 'Dharmapuri' },
    TuvhD70cDYY: { label: 'Dharwad', value: 'Dharwad' },
    Fl20ZcEwvVH: { label: 'Dhemaji', value: 'Dhemaji' },
    z4hWq6HmclY: { label: 'Dhenkanal', value: 'Dhenkanal' },
    yREzls0vTo4: { label: 'Dholpur', value: 'Dholpur' },
    HHPZ53bfid3: { label: 'Dhubri', value: 'Dhubri' },
    NWtt6XLx3tF: { label: 'Dhule', value: 'Dhule' },
    HFiCCqhskvf: { label: 'Diamondharbour HD', value: 'Diamondharbour HD' },
    ZpN3ieZQUh4: { label: 'Dibang Valley', value: 'Dibang Valley' },
    HgLXQFLaMgs: { label: 'Dibrugarh', value: 'Dibrugarh' },
    vpOUyyqgQNs: { label: 'difficile', value: 'difficile' },
    QPMfPXcLCSb: { label: 'Dima Hasao', value: 'Dima Hasao' },
    iLUC1HvAc3F: { label: 'Dimapur', value: 'Dimapur' },
    tmpvG7uE5AQ: { label: 'DIN', value: 'DIN' },
    WemKvPtRVS3: { label: 'Dindigul', value: 'Dindigul' },
    cGMFd5dyadN: { label: 'Dindori', value: 'Dindori' },
    XMN9j5pXnaM: { label: 'Disk diffusion', value: 'Disk diffusion' },
    fZdbuC0SsNX: { label: 'Dispatched', value: 'Dispatched' },
    rXwDqMXPwfd: { label: 'Dispatch pending', value: 'Pending' },
    AThz9amA8Ng: { label: 'Diu', value: 'Diu' },
    cuyFac8Cq2m: { label: 'Doda', value: 'Doda' },
    MSagmUp6zU8: { label: 'Drain Fluid', value: 'Drain Fluid' },
    JW45NtD0NL8: {
        label: 'Drug De-Addiction and Treatment',
        value: 'Drug De-Addiction and Treatment',
    },
    NzS98RfiXXn: { label: 'Dumka', value: 'Dumka' },
    lLCI7XYgP2S: { label: 'Dungapur', value: 'Dungapur' },
    Q8S4PtVKt0T: { label: 'Durg', value: 'Durg' },
    KNV1gE1uDdR: { label: 'dysenteriae', value: 'dysenteriae' },
    HEIqsYy1ZKF: { label: 'Ear Swab', value: 'Ear Swab' },
    v2F70LxroWo: { label: 'East Champaran', value: 'East Champaran' },
    ZGghvlonSmX: { label: 'East Delhi', value: 'East Delhi' },
    WWvo5R0GauZ: { label: 'East Garo Hills', value: 'East Garo Hills' },
    G3MW35KsjjP: { label: 'East Godavari', value: 'East Godavari' },
    D58M9LJIfTW: { label: 'East Kameng', value: 'East Kameng' },
    ewUpbMGuxOS: { label: 'East Khasi Hills', value: 'East Khasi Hills' },
    EVJGgYGZbNr: { label: 'East Siang', value: 'East Siang' },
    S0FaUl2sy8w: { label: 'East Sikkim', value: 'East Sikkim' },
    cgdhW6j58rR: { label: 'East Singhbhum', value: 'East Singhbhum' },
    yR52HiTCWdk: { label: 'Emergency Medicine', value: 'Emergency Medicine' },
    KhtN6Zfxor7: {
        label: 'Emergency Medicine and Trauma',
        value: 'Emergency Medicine and Trauma',
    },
    cOeb89BNuTI: { label: 'Emergency Surgery', value: 'Emergency Surgery' },
    lNdaOKp4rv0: { label: 'Endocrinology', value: 'Endocrinology' },
    JqAEw6apXUk: { label: 'Endometrium', value: 'Endometrium' },
    nAnz6zRXBNr: {
        label: 'Endotracheal aspirate (ETA)',
        value: 'Endotracheal aspirate (ETA)',
    },
    zUfPzKDDDPZ: { label: 'Endotracheal tube', value: 'Endotracheal tube' },
    LY3994rLcC5: { label: 'Enteritidis', value: 'Enteritidis' },
    KXNleAMi4La: { label: 'Enterobacter', value: 'Enterobacter' },
    BmMtJmOi1NM: { label: 'Enterobacter aerogenes', value: 'EAE' },
    iS4LfMCEFca: { label: 'Enterobacter aerogenes', value: 'EAE' },
    fA38qF9ESqn: { label: 'Enterobacter cloacae', value: 'ECL' },
    arDeSk8eLGD: { label: 'Enterobacter spp.', value: 'EN-' },
    ZnzQlfo9FNS: { label: 'Enterobacter spp.', value: 'EN-' },
    nb7E8cEsoiK: { label: 'Enterococcus', value: 'Enterococcus' },
    qNQVjF8INzn: { label: 'Enterococcus faecalis', value: 'EFA' },
    GzIyFeep8bf: { label: 'Enterococcus faecium', value: 'EFM' },
    z4CWciYk7Uz: { label: 'Enterococcus spp.', value: 'ENT' },
    thvCoh4qhMz: { label: 'enterocolitica', value: 'enterocolitica' },
    HHCI7e9LSyk: { label: 'epidermidis', value: 'epidermidis' },
    tnOFmn0tOaM: { label: 'Ernakulam', value: 'Ernakulam' },
    EPa6jUIHY2N: { label: 'Erode', value: 'Erode' },
    tha7Bfo4iQs: { label: 'Escherichia', value: 'Escherichia' },
    MgoARk5Djdl: { label: 'Escherichia coli', value: 'ECO' },
    yCNO4C6ppRC: { label: 'Escherichia coli', value: 'ECO' },
    Qfwa5HdtaVG: { label: 'Escherichia coli Diarrhoeagenic', value: 'ECOD' },
    sKhRxFMooJD: { label: 'Etah', value: 'Etah' },
    YhaNreBafAR: { label: 'Etawah', value: 'Etawah' },
    R1MAhULX29w: { label: 'Ethmoidal tissue', value: 'Ethmoidal tissue' },
    boGlSorazIG: { label: 'EUCAST', value: 'EUCAST' },
    a4dZztG2XoT: { label: 'Event', value: 'Event' },
    IgNturOWecM: { label: 'fabianii', value: 'fabianii' },
    qzJ5oHkpPbx: { label: 'faecalis', value: 'faecalis' },
    OMXsRfhKBaO: { label: 'Faeces', value: 'Faeces' },
    ovPsdqBZCLV: { label: 'faecium', value: 'faecium' },
    wTrceFpuFmC: { label: 'Faizabad', value: 'Faizabad' },
    itk2755IxBB: { label: 'famata', value: 'famata' },
    ZSM16GdgNLW: { label: 'Family medicine', value: 'Family medicine' },
    RDUj15lOFO7: { label: 'Faridabad', value: 'Faridabad' },
    QPY6SQijMSC: { label: 'Faridkot', value: 'Faridkot' },
    KrwgH98Lwoh: { label: 'Farrukhabad', value: 'Farrukhabad' },
    LQyCqv7on6J: { label: 'Fatehabad', value: 'Fatehabad' },
    pc55owveteA: { label: 'Fatehgarh Sahib', value: 'Fatehgarh Sahib' },
    OMQ3VOH3Apc: { label: 'Fatehpur', value: 'Fatehpur' },
    n3QiX0917op: { label: 'Fazilka', value: 'Fazilka' },
    kEwsxwxfRL0: { label: 'Female', value: 'Female' },
    BMIDPkqaApk: { label: 'Firozabad', value: 'Firozabad' },
    pyPr2CNMSRx: { label: 'Firozpur', value: 'Firozpur' },
    vEMHyFTEIBA: { label: 'flavus', value: 'flavus' },
    PjTNK8BFtwb: { label: 'flexneri', value: 'flexneri' },
    wnhiWxUiMGk: {
        label: 'Fluid from sterile site',
        value: 'Fluid from sterile site',
    },
    GLdBilhcYbD: { label: 'FNAC', value: 'FNAC' },
    xLa12I88P3P: { label: 'Food', value: 'Food' },
    XkbFAajhmZe: {
        label: 'Forensic Medicine and Toxicology',
        value: 'Forensic Medicine and Toxicology',
    },
    RQxQ5Vjo63J: { label: 'freundii', value: 'freundii' },
    xFlyjJX8AaG: { label: 'fumigatus', value: 'fumigatus' },
    nlTWG14Tu7f: { label: 'Gadag', value: 'Gadag' },
    yDywpua4Fec: { label: 'Gadchiroli', value: 'Gadchiroli' },
    D7OEusNlvPg: { label: 'Gajapati', value: 'Gajapati' },
    HXyAwqlpmxu: { label: 'Ganderbal', value: 'Ganderbal' },
    xy5dfMdrR3v: { label: 'Gandhinagar', value: 'Gandhinagar' },
    A3hDBRxdnOx: { label: 'Ganganagar', value: 'Ganganagar' },
    VFeBQkngeJm: { label: 'Ganjam', value: 'Ganjam' },
    dWU14qRdPsv: { label: 'Garhwa', value: 'Garhwa' },
    UyImtGDUgrc: { label: 'Gariaband', value: 'Gariaband' },
    XMdEPqD7x1q: { label: 'Gastric fluid', value: 'Gastric fluid' },
    VWJhdiUwv5J: { label: 'Gastroenterology', value: 'Gastroenterology' },
    DI324jT2GeN: {
        label: 'Gastro-intestinal and hepatobiliary surgical oncology',
        value: 'Gastro-intestinal and hepatobiliary surgical oncol',
    },
    cHX9yXSBCsU: { label: 'Gautam Buddh Nagar', value: 'Gautam Buddh Nagar' },
    ollHDHdcNkL: { label: 'Gaya', value: 'Gaya' },
    evTlKkuENfs: { label: 'General surgery', value: 'General surgery' },
    YYJNh2SwcJC: { label: 'Genital tract', value: 'Genital tract' },
    FcKHVkSo6Jg: { label: 'Geriatric medicine', value: 'Geriatric medicine' },
    A3R60FpziDE: { label: 'Geriatrics', value: 'Geriatrics' },
    mZ1jaBMPvY5: { label: 'Ghaziabad', value: 'Ghaziabad' },
    cqN1n9xpz4G: { label: 'Ghazipur', value: 'Ghazipur' },
    f84LiVR8riY: { label: 'Giridih', value: 'Giridih' },
    HJuBGWjsydq: { label: 'Gir Somnath', value: 'Gir Somnath' },
    ItC4FIdf7cc: { label: 'G.I. Surgery', value: 'G.I. Surgery' },
    rtaonfdGT9Q: { label: 'glabrata', value: 'glabrata' },
    fWg32gIqGun: { label: 'glutinis', value: 'glutinis' },
    d46myMRrmeH: { label: 'Goa', value: 'Goa' },
    rGdb2mpwoQ3: { label: 'Goalpara', value: 'Goalpara' },
    ljbc3GYIMeG: { label: 'Godda', value: 'Godda' },
    Fc66k8eSEmn: { label: 'Golaghat', value: 'Golaghat' },
    GBycVU1WB32: { label: 'Gomati', value: 'Gomati' },
    phmICXPhRps: { label: 'Gonda', value: 'Gonda' },
    zXkVHIDXM3z: { label: 'Gondia', value: 'Gondia' },
    DZ11mxMfoHN: { label: 'Gopalganj', value: 'Gopalganj' },
    C40yNNAwGBf: { label: 'Gorakhpur', value: 'Gorakhpur' },
    kZP1VYSpBLe: { label: 'Gorimedu PHC', value: 'Gorimedu PHC' },
    y4q70wX7L4A: { label: 'guilliermondii', value: 'guilliermondii' },
    dDJJF9z6zvg: { label: 'Gujarat', value: 'Gujarat' },
    sX9u6oqigBT: { label: 'Gulbarga', value: 'Gulbarga' },
    kpq7eu3Lr6F: { label: 'Gumla', value: 'Gumla' },
    GW380RQFumE: { label: 'Guna', value: 'Guna' },
    BgWWpil86b6: { label: 'Guntur', value: 'Guntur' },
    Am3nOxpNF5F: { label: 'Gurdaspur', value: 'Gurdaspur' },
    l83aNFpqWVs: { label: 'Gurgaon', value: 'Gurgaon' },
    A6VRE9OtjEp: { label: 'Gwalior', value: 'Gwalior' },
    o26TqplWayu: {
        label: 'Gynaecologic oncology',
        value: 'Gynaecologic oncology',
    },
    QWRwcHJmUBC: { label: 'haemolyticus', value: 'haemolyticus' },
    A0VajnFUl7i: { label: 'haemulonii', value: 'haemulonii' },
    ACzLg4Lt8YS: { label: 'Hafnia', value: 'Hafnia' },
    NTck1CBE8Wp: { label: 'Hafnia alvei', value: 'HAL' },
    NzduSQBiZnO: { label: 'Hafnia alvei', value: 'HAL' },
    E0Kw6CLvQBb: { label: 'Hailakandi', value: 'Hailakandi' },
    erOMTEUl1WB: { label: 'Hair', value: 'Hair' },
    PEkzi9HJEmI: { label: 'Hamirpur-HP', value: 'Hamirpur-HP' },
    SkODd72Alq8: { label: 'Hamirpur-UP', value: 'Hamirpur-UP' },
    PhpIqswKw7r: {
        label: 'Hand and Leprosy reconstructive surgery',
        value: 'Hand and Leprosy reconstructive surgery',
    },
    y8jMpeNHoN7: { label: 'hansenii', value: 'hansenii' },
    VAyyCBuNCIy: { label: 'Hanumangarh', value: 'Hanumangarh' },
    sRF2ytPGBef: {
        label: 'Hapur (Panchsheel Nagar)',
        value: 'Hapur (Panchsheel Nagar)',
    },
    TjUySUdqsP4: { label: 'Harda', value: 'Harda' },
    XVZDSSqDvMJ: { label: 'Hardoi', value: 'Hardoi' },
    kag6xifF6AY: { label: 'Haridwar', value: 'Haridwar' },
    v0xJgjdyzuG: { label: 'Haryana', value: 'Haryana' },
    YUmAnhpwFdh: { label: 'Hassan', value: 'Hassan' },
    CHfKUrQF6Pu: {
        label: 'Hathras (Mahamaya Nagar)',
        value: 'Hathras (Mahamaya Nagar)',
    },
    CQ7Gynp9i8W: { label: 'Haveri district', value: 'Haveri district' },
    Wv7XYtdzSLD: { label: 'Hazaribag', value: 'Hazaribag' },
    teSYS02QYmw: {
        label: 'Head and Neck Surgical Oncology',
        value: 'Head and Neck Surgical Oncology',
    },
    em1U9twKZjU: {
        label: 'Health care associated infection',
        value: 'Health care associated',
    },
    pmYttW0jveK: { label: 'Heidelberg', value: 'Heidelberg' },
    APwWNaDpDa5: { label: 'Hematology', value: 'Hematology' },
    mpaVLMw8hpe: { label: 'Hepatology', value: 'Hepatology' },
    LGZzvZu9vo1: {
        label: 'High Dependency Unit (HDU)',
        value: 'High Dependency Unit (HDU)',
    },
    c27HB41eQ83: { label: 'Himachal Pradesh', value: 'Himachal Pradesh' },
    vlcRl1lC72b: { label: 'Hingoli', value: 'Hingoli' },
    c2kzFMJqQ9l: { label: 'Hissar', value: 'Hissar' },
    Bsg5vQ2hjy2: { label: 'hominis', value: 'hominis' },
    kjCitN2jQV5: { label: 'homothallicus', value: 'homothallicus' },
    TgqiNHTbjwO: { label: 'Hooghly', value: 'Hooghly' },
    WC6jSa3GpL4: { label: 'Hoshangabad', value: 'Hoshangabad' },
    OkqFvOYu3QD: { label: 'Hoshiarpur', value: 'Hoshiarpur' },
    G2ULlDR9T0w: { label: 'Howrah', value: 'Howrah' },
    n7FK4lsAVpo: { label: 'Human', value: 'Human' },
    Y85cjzmNqnp: { label: 'Hyderabad', value: 'Hyderabad' },
    yAsk8qsuUnA: { label: 'ICTD fluid', value: 'ICTD fluid' },
    gJmrVtGpNKO: { label: 'ICU', value: 'ICU' },
    yoZK8poO8NQ: { label: 'ICU', value: 'ICU' },
    tv1osf6rFj1: { label: 'Idukki', value: 'Idukki' },
    T83aN6L82Xg: { label: 'Imphal East', value: 'Imphal East' },
    QTqQt4PeK5S: { label: 'Imphal West', value: 'Imphal West' },
    id4DvXZUQQ3: { label: 'Indore', value: 'Indore' },
    jnuLEryziCA: { label: 'Instrument', value: 'Instrument' },
    ytDrcE16TDM: { label: 'intermedia', value: 'intermedia' },
    oESqTPfHKXh: { label: 'Intermediate', value: 'Intermediate' },
    rxe4e8m1oo1: { label: 'Internal Medicine', value: 'Internal Medicine' },
    dvejQAH9oOl: { label: 'Intestinal fluid', value: 'Intestinal fluid' },
    TwOAP1bNm0X: {
        label: 'Intracostal tube fluid',
        value: 'Intracostal tube fluid',
    },
    zykS43e0JC5: {
        label: 'Intra operative bile',
        value: 'Intra operative bile',
    },
    RPLDjcN5BL5: {
        label: 'Intra operative fluid',
        value: 'Intra operative fluid',
    },
    EXbmIF4FdqM: { label: 'Iobectomy tissue', value: 'Iobectomy tissue' },
    SEALT9mI4qf: { label: 'IRCH (Malignancy)', value: 'IRCH (Malignancy)' },
    Gjwnjy8DRTP: { label: 'Isolate', value: 'Isolate' },
    oWRoc0UmTqX: { label: 'Jabalpur', value: 'Jabalpur' },
    Lryh6p2zabE: { label: 'jadinii', value: 'jadinii' },
    V2u7SJnStHv: { label: 'Jagatsinghpur', value: 'Jagatsinghpur' },
    CaEOCONROW2: { label: 'Jaintia Hills', value: 'Jaintia Hills' },
    id1h5AyKND4: { label: 'Jaipur', value: 'Jaipur' },
    CxIS59Ogjm4: { label: 'Jaisalmer', value: 'Jaisalmer' },
    BLc9mnS2MxT: { label: 'Jajpur', value: 'Jajpur' },
    cCEFyeGlJa2: { label: 'Jalandhar', value: 'Jalandhar' },
    zvrBh04K5yD: { label: 'Jalaun', value: 'Jalaun' },
    kXrSgs8TAx1: { label: 'Jalgaon', value: 'Jalgaon' },
    SIg2j3pOXYq: { label: 'Jalna', value: 'Jalna' },
    wQJozOy4apA: { label: 'Jalore', value: 'Jalore' },
    mcyuRmzs9A2: { label: 'Jalpaiguri', value: 'Jalpaiguri' },
    ucHNJQ0iDsU: { label: 'Jammu', value: 'Jammu' },
    rrLmOTBSmpT: { label: 'Jammu and Kashmir', value: 'Jammu and Kashmir' },
    fWu8ARHkPSi: { label: 'Jamnagar', value: 'Jamnagar' },
    oY4HfoCUrO2: { label: 'Jamtara', value: 'Jamtara' },
    jnazZalNGol: { label: 'Jamui', value: 'Jamui' },
    dwDg1duL1Ip: { label: 'Janjgir-Champa', value: 'Janjgir-Champa' },
    Fbd5tV1iF36: { label: 'Jashpur', value: 'Jashpur' },
    xEx9OdA7Mte: { label: 'Jaunpur district', value: 'Jaunpur district' },
    IgpSjbdVZ1j: { label: 'Jehanabad', value: 'Jehanabad' },
    XwRKKRMSE80: { label: 'jejuni', value: 'jejuni' },
    IH8XxCLFYPI: { label: 'Jhabua', value: 'Jhabua' },
    RDYiZUdT7ms: { label: 'Jhajjar', value: 'Jhajjar' },
    CTMs4zd5J0g: { label: 'Jhalawar', value: 'Jhalawar' },
    YD8VjLiFr95: { label: 'Jhansi', value: 'Jhansi' },
    vDmSrZHVK6u: { label: 'Jhargram', value: 'Jhargram' },
    LMKRH3Z0xK0: { label: 'Jharkhand', value: 'Jharkhand' },
    yeENU3O1M5K: { label: 'Jharsuguda', value: 'Jharsuguda' },
    WPC5R5TdBQE: { label: 'Jhunjhunu', value: 'Jhunjhunu' },
    vWwjqxITfpx: { label: 'Jind', value: 'Jind' },
    zZZPQEWlz8s: { label: 'Jodhpur', value: 'Jodhpur' },
    xPNDvmAsKe5: { label: 'Joint Fluid', value: 'Joint Fluid' },
    TgGmbGLuAVR: { label: 'Jorhat', value: 'Jorhat' },
    aaEedDk3GOX: { label: 'Junagadh', value: 'Junagadh' },
    cCaIdKTF4kZ: { label: 'Jyotiba Phule Nagar', value: 'Jyotiba Phule Nagar' },
    fwqTzuAeUIv: {
        label: 'Kabirdham (formerly Kawardha)',
        value: 'Kabirdham (formerly Kawardha)',
    },
    owpUpXAqpPV: { label: 'Kadapa', value: 'Kadapa' },
    hLAsB9x1OIW: { label: 'Kaimur', value: 'Kaimur' },
    yp93uUZlAYf: { label: 'Kaithal', value: 'Kaithal' },
    jnxKwQ4x1Lx: { label: 'Kalahandi', value: 'Kalahandi' },
    QGbspKnGFWT: { label: 'Kalapet PHC', value: 'Kalapet PHC' },
    i8zP97lSvlR: { label: 'Kalimpong', value: 'Kalimpong' },
    kgkokH0fGoi: { label: 'Kamrup', value: 'Kamrup' },
    Hht1BT6MmUw: { label: 'Kamrup Metropolitan', value: 'Kamrup Metropolitan' },
    LyKTYfcAvby: { label: 'Kanchipuram', value: 'Kanchipuram' },
    Xz0AauKH7D0: { label: 'Kandhamal', value: 'Kandhamal' },
    YrMmXvnBNtj: { label: 'Kangra', value: 'Kangra' },
    xCC7SVXst3A: { label: 'Kanker', value: 'Kanker' },
    SMhoOcEcwu8: { label: 'Kannauj', value: 'Kannauj' },
    P0XaHrkXL7B: { label: 'Kannur', value: 'Kannur' },
    gH8YxMwDQWL: {
        label: 'Kanpur Dehat (Ramabai Nagar)',
        value: 'Kanpur Dehat (Ramabai Nagar)',
    },
    wsCzftjGR6K: { label: 'Kanpur Nagar', value: 'Kanpur Nagar' },
    k5Lx9P8Z0Iy: { label: 'Kanshi Ram Nagar', value: 'Kanshi Ram Nagar' },
    dbZ1T85UO1A: { label: 'Kanyakumari', value: 'Kanyakumari' },
    u4ZIzJlJ8jX: { label: 'Kapurthala', value: 'Kapurthala' },
    B6G4NFXF1ni: { label: 'Karaikal', value: 'Karaikal' },
    sBFj1W1YRaf: { label: 'Karaikalmedu PHC', value: 'Karaikalmedu PHC' },
    PfTEEbLF1JN: { label: 'Karauli', value: 'Karauli' },
    uk3YOrUs0Cs: { label: 'Karayambuthur PHC', value: 'Karayambuthur PHC' },
    HikAogLqElo: { label: 'Karbi Anglong', value: 'Karbi Anglong' },
    oMibuBGzyoj: { label: 'Kargil', value: 'Kargil' },
    vNAS2olwX7y: { label: 'Karimganj', value: 'Karimganj' },
    bHZt85OPRij: { label: 'Karimnagar', value: 'Karimnagar' },
    Te8CNNMAjk6: { label: 'Karkalampakkam CHC', value: 'Karkalampakkam CHC' },
    IdHupSTbjfC: { label: 'Karnal', value: 'Karnal' },
    GUbYXezrpPY: { label: 'Karnataka', value: 'Karnataka' },
    rqKPZLQ5DDo: { label: 'Karur', value: 'Karur' },
    ZIRRytbv8JX: { label: 'Kasaragod', value: 'Kasaragod' },
    CxFg636mVYv: { label: 'Kathua', value: 'Kathua' },
    QvDrLpW8OzS: { label: 'Katihar', value: 'Katihar' },
    LxDAREktbrf: { label: 'Katni', value: 'Katni' },
    WWPNzAIQoVp: { label: 'Katterikuppam PHC', value: 'Katterikuppam PHC' },
    oYKY0oQae8P: { label: 'Kaushambi', value: 'Kaushambi' },
    WnKWmJslmKI: { label: 'kefyr', value: 'kefyr' },
    ER24hJruRh7: { label: 'Kendrapara', value: 'Kendrapara' },
    QPGi54SHhWk: {
        label: 'Kendujhar (Keonjhar)',
        value: 'Kendujhar (Keonjhar)',
    },
    nxBUuj1IjO6: { label: 'Kerala', value: 'Kerala' },
    MjRPaHeMM3t: { label: 'Khagaria', value: 'Khagaria' },
    cwDmkPYad8c: { label: 'Khammam', value: 'Khammam' },
    pVrQAy2cMff: {
        label: 'Khandwa (East Nimar)',
        value: 'Khandwa (East Nimar)',
    },
    vuz7gSkwnya: {
        label: 'Khargone (West Nimar)',
        value: 'Khargone (West Nimar)',
    },
    kXALiyP99bE: { label: 'Kheda', value: 'Kheda' },
    nQP8vJhIk3d: { label: 'Khordha', value: 'Khordha' },
    ythI0bfgjO8: { label: 'Khowai', value: 'Khowai' },
    c3OZSZnULzX: { label: 'Khunti', value: 'Khunti' },
    luBUGgsy4I1: { label: 'Kinnaur', value: 'Kinnaur' },
    ZsnD1TeO8Zc: { label: 'Kiphire', value: 'Kiphire' },
    ZfCx5TJi5ZF: { label: 'Kirumampakkam PHC', value: 'Kirumampakkam PHC' },
    P2Sg7AQwZTe: { label: 'Kishanganj', value: 'Kishanganj' },
    tUbP83WhGg9: { label: 'Kishtwar', value: 'Kishtwar' },
    E5kOkcq4jaM: { label: 'Klebsiella', value: 'Klebsiella' },
    amHqLMTC4gQ: { label: 'Klebsiella oxytoca', value: 'KOX' },
    Vb3m800Y9zQ: { label: 'Klebsiella pneumoniae', value: 'KPN' },
    CdK0zZvyVij: { label: 'Klebsiella pneumoniae', value: 'KPN' },
    qhr9f9B09vq: { label: 'Klebsiella spp.', value: 'KL-' },
    l2Lezng9eJx: { label: 'Klebsiella spp.', value: 'KL-' },
    wpwmGfNbjH2: { label: 'Kodagu', value: 'Kodagu' },
    fDjlTq7ivDV: { label: 'Kodamaea', value: 'Kodamaea' },
    o72jRjZ9grz: { label: 'Kodamaea ohmeri', value: 'KOH' },
    TFkq4qMxuSo: { label: 'Koderma', value: 'Koderma' },
    o1nP2yBxeLp: { label: 'Kohima', value: 'Kohima' },
    hPAGjN2f5gj: { label: 'Kokrajhar', value: 'Kokrajhar' },
    HPbDSH1n49g: { label: 'Kolar', value: 'Kolar' },
    d3P9PzxV8NP: { label: 'Kolasib', value: 'Kolasib' },
    ovoSqWCPXUT: { label: 'Kolhapur', value: 'Kolhapur' },
    sCIMUxN9Z5Z: { label: 'Kolkata', value: 'Kolkata' },
    QgaqJkHzIuA: { label: 'Kollam', value: 'Kollam' },
    Za4NVcTYeci: { label: 'Kondagaon', value: 'Kondagaon' },
    e4oeREjpOEM: { label: 'Koodapakkam PHC', value: 'Koodapakkam PHC' },
    bsNoDNTqOnX: { label: 'Koppal', value: 'Koppal' },
    QJMW9a7ktgu: { label: 'Koraput', value: 'Koraput' },
    yPiIywyOweo: { label: 'Korba', value: 'Korba' },
    b801YjCWtfc: { label: 'Koriya', value: 'Koriya' },
    tIGKTxLDfIl: { label: 'Kosapalayam PHC', value: 'Kosapalayam PHC' },
    mKqMgcvotDw: { label: 'koseri', value: 'koseri' },
    cSCz5bpJHw3: { label: 'Kota', value: 'Kota' },
    QS4GKVpJFvU: { label: 'Kottayam', value: 'Kottayam' },
    Lyqgr7TJaoK: { label: 'Kozhikode', value: 'Kozhikode' },
    EUMTNjOQAFg: { label: 'Kra Daadi', value: 'Kra Daadi' },
    N0YB5mcF078: { label: 'Krishna', value: 'Krishna' },
    yl3C6m7mVeE: { label: 'Krishnagiri', value: 'Krishnagiri' },
    FYz3q4HkDo8: { label: 'krusei', value: 'krusei' },
    YtPtiyN6iVC: { label: 'kudriavzevii', value: 'kudriavzevii' },
    rclPTrEQgzM: { label: 'Kulgam', value: 'Kulgam' },
    wJsFC3cQ1iF: { label: 'Kullu', value: 'Kullu' },
    b3RiV7e3jGT: { label: 'Kupwara', value: 'Kupwara' },
    d5hk7TN7t7J: { label: 'Kurnool', value: 'Kurnool' },
    mdiFjwzqghl: { label: 'Kurukshetra', value: 'Kurukshetra' },
    HXUzQ4hB8Eh: { label: 'Kurung Kumey', value: 'Kurung Kumey' },
    NUEhzO5Q7Pv: { label: 'Kushinagar', value: 'Kushinagar' },
    MYZAaDohNwq: { label: 'Kutch', value: 'Kutch' },
    bAW8pMsYwMY: { label: 'Lahaul and Spiti', value: 'Lahaul and Spiti' },
    lntVaeRFh4K: { label: 'Lakhimpur', value: 'Lakhimpur' },
    jupWmRXhY3d: { label: 'Lakhimpur Kheri', value: 'Lakhimpur Kheri' },
    o5EqbedtwB2: { label: 'Lakhisarai', value: 'Lakhisarai' },
    BSXpw6DZmPz: { label: 'Lakshadweep', value: 'Lakshadweep' },
    RzFmzNewFKZ: { label: 'Lakshadweep', value: 'Lakshadweep' },
    dFI2tX7lE0E: { label: 'Lalitpur', value: 'Lalitpur' },
    Tf6u7mNrc7d: { label: 'Latehar', value: 'Latehar' },
    meOlNsVw8A5: { label: 'Latur', value: 'Latur' },
    ydtNd5M5Z3J: { label: 'Lawngtlai', value: 'Lawngtlai' },
    ykBO2Hiyz3I: { label: 'Lawspet PHC', value: 'Lawspet PHC' },
    JPT5rhBXIJE: { label: 'Leh', value: 'Leh' },
    Zb9lxWMKOl6: { label: 'lipolytica', value: 'lipolytica' },
    onRqroa6x15: { label: 'Lohardaga', value: 'Lohardaga' },
    m5zg5bGFlFg: { label: 'Lohit', value: 'Lohit' },
    QfK5JY2Eqnz: { label: 'Longding', value: 'Longding' },
    N6PpjwQ6TNr: { label: 'Longleng', value: 'Longleng' },
    wrZHGG3Z2gy: {
        label: 'Low Cost Effective Care Unit (LCECU)',
        value: 'Low Cost Effective Care Unit (LCECU)',
    },
    csU4INnGgTb: { label: 'Lower Dibang Valley', value: 'Lower Dibang Valley' },
    vEiCPmNC8I4: { label: 'Lower Subansiri', value: 'Lower Subansiri' },
    kxw2FhZTXro: { label: 'Lucknow', value: 'Lucknow' },
    ApjPrn1Hbbk: { label: 'Ludhiana', value: 'Ludhiana' },
    UgMcX3CYgEM: { label: 'lugdunensis', value: 'lugdunensis' },
    ivx4YExRo12: { label: 'Lung aspirate', value: 'Lung aspirate' },
    BwBayEX4NGJ: { label: 'Lunglei', value: 'Lunglei' },
    wPMKuTjGrn0: { label: 'lusitaniae', value: 'lusitaniae' },
    hj55MiCP1IG: { label: 'lwoffii', value: 'lwoffii' },
    dz9vUMXGBD4: { label: 'Lymph node', value: 'Lymph node' },
    X9WUGxS6MXW: { label: 'Madhepura', value: 'Madhepura' },
    ezWHVwfGpSI: { label: 'Madhubani', value: 'Madhubani' },
    LR3XAGg8cM1: { label: 'Madhya Pradesh', value: 'Madhya Pradesh' },
    Y71TAmT7cNN: { label: 'Madukarai PHC', value: 'Madukarai PHC' },
    es4Jw1B987T: { label: 'Madurai', value: 'Madurai' },
    j8fRMSwmfBN: { label: 'Maharajganj', value: 'Maharajganj' },
    akqlOLJebXL: { label: 'Maharashtra', value: 'Maharashtra' },
    Vj6140jegAa: { label: 'Mahasamund', value: 'Mahasamund' },
    h8wwoLzILCv: { label: 'Mahbubnagar', value: 'Mahbubnagar' },
    fRxM1LOo67x: { label: 'Mahe', value: 'Mahe' },
    JYjBCaR1eiS: { label: 'Mahendragarh', value: 'Mahendragarh' },
    RdNC5bA2kL9: { label: 'Mahisagar', value: 'Mahisagar' },
    DTzhXaB44gi: { label: 'Mahoba', value: 'Mahoba' },
    fsnXi9fmAAg: { label: 'Mainpuri', value: 'Mainpuri' },
    GBXt7gKL0XY: { label: 'Malappuram', value: 'Malappuram' },
    oHSlYEni1VZ: { label: 'Maldah', value: 'Maldah' },
    tVXOqIKOlr4: { label: 'Male', value: 'Male' },
    wBnvAE1Fe4f: { label: 'Malkangiri', value: 'Malkangiri' },
    ZFhpwlY1sf7: { label: 'maltophilia', value: 'maltophilia' },
    YDZNrZzKkwW: { label: 'Mamit', value: 'Mamit' },
    Jufv8cAYd8L: { label: 'Mandi', value: 'Mandi' },
    xe5hu8NA6q6: { label: 'Mandla', value: 'Mandla' },
    q86W9XsqGbV: { label: 'Mandsaur', value: 'Mandsaur' },
    kQmsw5QHoHd: { label: 'Mandya', value: 'Mandya' },
    s6aJsmWO7je: { label: 'Manipur', value: 'Manipur' },
    FqH0xEV9PTs: { label: 'Mannadipet CHC', value: 'Mannadipet CHC' },
    vtQ6W3RtBaf: { label: 'Mansa', value: 'Mansa' },
    Sa4kWEEY2S1: { label: 'marcescens', value: 'marcescens' },
    LcqaTta3a0w: { label: 'Mathura', value: 'Mathura' },
    BCUdA1gwovz: { label: 'Mau', value: 'Mau' },
    mAJDfD9wF5A: {
        label: 'Maxillary alveolar tissue',
        value: 'Maxillary alveolar tissue',
    },
    tXUb6MsC4gb: { label: 'Maxillary sinus', value: 'Maxillary sinus' },
    QSyNkPD4Ni8: { label: 'Mayurbhanj', value: 'Mayurbhanj' },
    w33wFTsffCY: {
        label: 'Mechanical ventilator',
        value: 'Mechanical ventilator',
    },
    BvBSuhgmgZq: { label: 'Medak', value: 'Medak' },
    DoaUQVlqwJl: {
        label: 'Medical Biometrics and Informatics (Biostatistics)',
        value: 'Medical Biometrics and Informatics (Biostatistics)',
    },
    OjLiV8fqLKo: { label: 'Medical Education', value: 'Medical Education' },
    OufgTdqrmLj: {
        label: 'Medical Gastroenterology',
        value: 'Medical Gastroenterology',
    },
    mfMTu2EhGMZ: { label: 'Medical Oncology', value: 'Medical Oncology' },
    QAukBOFqPNb: { label: 'Medicine', value: 'Medicine' },
    lZmaFe4zeOL: { label: 'Meerut', value: 'Meerut' },
    yOIY4QVoYcC: { label: 'Meghalaya', value: 'Meghalaya' },
    mToGITovGGv: { label: 'Mehsana', value: 'Mehsana' },
    Y3HrtG2nyaW: { label: 'mentagrophytes', value: 'mentagrophytes' },
    MnWXvpOAj1r: { label: 'Mettupalayam PHC', value: 'Mettupalayam PHC' },
    SXfmnK5uDK1: { label: 'Mewat', value: 'Mewat' },
    l6FN1Fds6BC: { label: 'MIC', value: 'MIC' },
    FqjbWCfhR8O: { label: 'Microbiology', value: 'Microbiology' },
    uBy72iFMYT5: { label: 'Micrococcus sp.', value: 'MIC' },
    aUE13Iaz44R: { label: 'microsporus', value: 'microsporus' },
    Za1fEcGhsfE: { label: 'mirabilis', value: 'mirabilis' },
    eqK0UQgqnyh: { label: 'Mirzapur', value: 'Mirzapur' },
    QKOcpXFUAgR: { label: 'Mixed bacterial species present', value: 'MIX' },
    g7M3PM2GNgQ: { label: 'Mizoram', value: 'Mizoram' },
    bhZN7Ln6ATo: { label: 'Moga', value: 'Moga' },
    elONinxz7AA: { label: 'Mohali', value: 'Mohali' },
    O5DKJ6vl30M: { label: 'Mokokchung', value: 'Mokokchung' },
    sTDHSFOmQgp: { label: 'Mon', value: 'Mon' },
    XtnpXdPypLk: { label: 'Moradabad', value: 'Moradabad' },
    MmCVnN74QJR: { label: 'Morbi', value: 'Morbi' },
    bkYBy6EEiC2: { label: 'Morena', value: 'Morena' },
    PVKlWVLMYin: { label: 'Morganella', value: 'Morganella' },
    swoHb1TKmsi: { label: 'Morganella morganii', value: 'MMO' },
    ARlL94e42I0: { label: 'Morganella morganii', value: 'MMO' },
    kKwsaRbnDWC: { label: 'morganii', value: 'morganii' },
    OVHoY5sCcD7: { label: 'Morigaon', value: 'Morigaon' },
    STaHp8U3EjS: { label: 'mucilaginosa', value: 'mucilaginosa' },
    vOHT8HmINOM: { label: 'mucoides', value: 'mucoides' },
    Z7P6GG6G78A: { label: 'Mudaliarpet PHC', value: 'Mudaliarpet PHC' },
    fA0et1yRhcy: { label: 'Mumbai', value: 'Mumbai' },
    Bs9c1Bun7Ch: { label: 'Mungeli', value: 'Mungeli' },
    HwjxMDbCv1O: { label: 'Munger', value: 'Munger' },
    EDuS9xjfmDd: { label: 'Murshidabad', value: 'Murshidabad' },
    PJLJAevUagC: { label: 'Murungapakkam PHC', value: 'Murungapakkam PHC' },
    Kk71jM9gC3o: { label: 'Muthialpet PHC', value: 'Muthialpet PHC' },
    ThEs5TqSHRH: { label: 'Muzaffarnagar', value: 'Muzaffarnagar' },
    IRN0yZKhS6t: { label: 'Muzaffarpur', value: 'Muzaffarpur' },
    LzuM8IanSom: { label: 'Myroides sp.', value: 'MYR' },
    k0xAN8sHFpd: { label: 'Mysore', value: 'Mysore' },
    f2Qr2y2spqa: { label: 'Nabarangpur', value: 'Nabarangpur' },
    HlIR4L2qs38: { label: 'Nadia', value: 'Nadia' },
    xBHmQGZ8PNk: { label: 'Nagaland', value: 'Nagaland' },
    G5RsdGXZQeR: { label: 'Nagaon', value: 'Nagaon' },
    FAFaoLDlYqk: { label: 'Nagapattinam', value: 'Nagapattinam' },
    isuremN0rt0: { label: 'Nagaur', value: 'Nagaur' },
    WjX3VQUZXhI: { label: 'Nagpur', value: 'Nagpur' },
    BTBnvuQVMkk: { label: 'Nail', value: 'Nail' },
    G2HdnOVoCw1: { label: 'Nainital', value: 'Nainital' },
    jXJbHD1XqQA: { label: 'Nalanda', value: 'Nalanda' },
    MlUUjbff7hu: { label: 'Nalbari', value: 'Nalbari' },
    bbteu1PkYCE: { label: 'Nalgonda', value: 'Nalgonda' },
    lmac59ltG6K: { label: 'Namakkal', value: 'Namakkal' },
    swHTPQsIuYq: { label: 'Namsai', value: 'Namsai' },
    SG1QHdwpENz: { label: 'Nanded', value: 'Nanded' },
    nhuupPc2OMc: { label: 'Nandigram HD', value: 'Nandigram HD' },
    teSvoECoZxu: { label: 'Nandurbar', value: 'Nandurbar' },
    NQfzFWPEcVe: { label: 'Narayanpur', value: 'Narayanpur' },
    ZgicmV5qnGn: { label: 'Narmada', value: 'Narmada' },
    B1NRHQt4KaR: { label: 'Narsinghpur', value: 'Narsinghpur' },
    O4rppdJOJml: { label: 'Nasal scrapping', value: 'Nasal scrapping' },
    ZFkPFV85yiP: { label: 'Nasal tissue', value: 'Nasal tissue' },
    P8q3JLKOjHj: { label: 'Nashik', value: 'Nashik' },
    CapMBkUIohf: { label: 'Navsari', value: 'Navsari' },
    iyQsRBJ19th: { label: 'Nawada', value: 'Nawada' },
    s27XK63v2EL: { label: 'Nawanshahr', value: 'Nawanshahr' },
    lgawal6wpfc: { label: 'Nayagarh', value: 'Nayagarh' },
    TQTARAR3Fjj: { label: 'Necrosum', value: 'Necrosum' },
    fJAa9i8SbfD: { label: 'Needle aspirate', value: 'Needle aspirate' },
    iJmmy16jstU: { label: 'Neemuch', value: 'Neemuch' },
    iIDXiEUO8mQ: { label: 'Negative', value: 'Negative' },
    ThyNEiWZrBY: { label: 'NEO', value: 'NEO' },
    zUjtk4GTom8: { label: 'neoformans', value: 'neoformans' },
    HTX2877h8BU: {
        label: 'neoformans var gattii',
        value: 'neoformans var gattii',
    },
    dgKdvAl0oWq: {
        label: 'neoformans var grubii',
        value: 'neoformans var grubii',
    },
    aPfm1yd9C5n: { label: 'Neonatology', value: 'Neonatology' },
    uKRlh4iKs0S: { label: 'Nephrology', value: 'Nephrology' },
    bhc5SmEJgDa: { label: 'Nettapakkam PHC', value: 'Nettapakkam PHC' },
    CMe2pI2ZB9n: { label: 'Neurology', value: 'Neurology' },
    TgpFCOlnvqS: { label: 'Neurosciences', value: 'Neurosciences' },
    aId7OBs5wr6: { label: 'Neurosurgery', value: 'Neurosurgery' },
    XxAvrU2UXyc: { label: 'New Delhi', value: 'New Delhi' },
    OQW6DvGh7A0: { label: 'Newport', value: 'Newport' },
    JqMYm3gJJ8n: { label: 'Nicobar', value: 'Nicobar' },
    x4P71bWiaA0: { label: 'nidulans', value: 'nidulans' },
    oj0CzBx0IJj: { label: 'niger', value: 'niger' },
    vSipQeyyFzk: { label: 'Nilgiris', value: 'Nilgiris' },
    cRDhUgZMeeN: { label: 'nivariensis', value: 'nivariensis' },
    ZfTQzpZrrfr: { label: 'Nizamabad', value: 'Nizamabad' },
    Riar01GboPD: { label: 'No', value: 'No' },
    IKgVWSXWBi3: { label: 'North 24 Parganas', value: 'North 24 Parganas' },
    OkJiIyWrHsz: {
        label: 'North and Middle Andaman',
        value: 'North and Middle Andaman',
    },
    FXYmd20QoLQ: { label: 'North Delhi', value: 'North Delhi' },
    Y2YXbCzyr4t: { label: 'North East Delhi', value: 'North East Delhi' },
    jKmtMBFNwWg: { label: 'North Garo Hills', value: 'North Garo Hills' },
    ko3hA8fBVJU: { label: 'North Goa', value: 'North Goa' },
    EaPktlaj8nJ: { label: 'North Sikkim', value: 'North Sikkim' },
    KBCe2bbBq47: { label: 'North Tripura', value: 'North Tripura' },
    aAXUtmJh23U: { label: 'North West Delhi', value: 'North West Delhi' },
    nrgz47asBKy: { label: 'Not known', value: 'Not known' },
    iqGZWck2KC8: { label: 'Nuapada', value: 'Nuapada' },
    UNXl8Drtn6E: { label: 'Nuclear Medicine', value: 'Nuclear Medicine' },
    nqPI0UE71qR: {
        label: 'Obstetrics and Gynaecology',
        value: 'Obstetrics and Gynaecology',
    },
    MzAMMRPjp0D: { label: 'Ocular-deep', value: 'Ocular-deep' },
    jE73ak2LioK: { label: 'Ocular-superficial', value: 'Ocular-superficial' },
    FGQDG1RkqQU: { label: 'Odiensalai PHC', value: 'Odiensalai PHC' },
    l9taxhgAtNk: { label: 'Odisha', value: 'Odisha' },
    EbX9YAz7Wm8: { label: 'ohmeri', value: 'ohmeri' },
    X59YdS1LLut: { label: 'OPD', value: 'OPD' },
    SuObNVgKSDF: { label: 'Ophthalmology', value: 'Ophthalmology' },
    Q1hs7bpbVyR: { label: 'Oral cavity crust', value: 'Oral cavity crust' },
    pqBtjFIah62: {
        label: 'Oral health (Dentistry)',
        value: 'Oral health (Dentistry)',
    },
    fTLT6A7TO84: { label: 'Orthopaedic Surgery', value: 'Orthopaedic Surgery' },
    vtPzoRQ64bs: { label: 'Orthopedics', value: 'Orthopedics' },
    GXZGS2cBUFt: { label: 'oryzae', value: 'oryzae' },
    FEcRucsKjYk: { label: 'Osmanabad', value: 'Osmanabad' },
    IrcGUfiAIOm: { label: 'Others', value: 'Others' },
    qtsx4H7zfcB: { label: 'Others', value: 'Others' },
    yuLTeBSoTRz: { label: 'Others', value: 'Others' },
    Wb1McIicdjE: { label: 'Others', value: 'Others' },
    ULk0mNwDiy6: { label: 'Others', value: 'Others' },
    tSWyLYoiIWu: {
        label: 'Other vascular access lines',
        value: 'Other vascular access lines',
    },
    CtG96ET06uI: {
        label: 'Otolaryngology (ENT)',
        value: 'Otolaryngology (ENT)',
    },
    d3ZjPZ46yEZ: { label: 'oxytoca', value: 'oxytoca' },
    b2kftVRFagc: { label: 'Pakur', value: 'Pakur' },
    wI1eSs0Fznb: { label: 'Palakkad', value: 'Palakkad' },
    q79sksaDqaB: { label: 'Palamu', value: 'Palamu' },
    apGm7vCSX1j: { label: 'Palatal mucosa', value: 'Palatal mucosa' },
    f0mHxfir2M9: { label: 'Palatal scrapping', value: 'Palatal scrapping' },
    QV4iDQ24wfH: { label: 'Palghar', value: 'Palghar' },
    vVAv9OMHMWq: { label: 'Pali', value: 'Pali' },
    FYvr60Sixtv: { label: 'Palwal', value: 'Palwal' },
    X85wo5NXCP4: { label: 'Panchkula', value: 'Panchkula' },
    QspZrPeL7WQ: { label: 'Panchmahal', value: 'Panchmahal' },
    Ni5tb7weBEn: {
        label: 'Pancreatic drain fluid',
        value: 'Pancreatic drain fluid',
    },
    Vko33Kld0eH: { label: 'Panipat', value: 'Panipat' },
    Z629w2FGLEZ: { label: 'Panna', value: 'Panna' },
    JenuBpyzH8m: { label: 'Pantoea agglomerans', value: 'EAG' },
    leUlkGHmTFu: { label: 'Papum Pare', value: 'Papum Pare' },
    a9ZgqdDQmIe: { label: 'parahaemolyticus', value: 'parahaemolyticus' },
    Y1SyZY4UC9w: { label: 'parapsilosis', value: 'parapsilosis' },
    Q5jFkCXeVR7: { label: 'pararugosa', value: 'pararugosa' },
    X5CbRYHOKJ5: { label: 'Paratyphi A', value: 'Paratyphi A' },
    cIcjufrkkHD: { label: 'Parbhani', value: 'Parbhani' },
    lzdzmsYnHd3: { label: 'Paschim Bardhaman', value: 'Paschim Bardhaman' },
    iQdUDO0qlZo: { label: 'Paschim Medinipur', value: 'Paschim Medinipur' },
    GAdOSuLhTrm: { label: 'Patan', value: 'Patan' },
    xkIHPAPetol: { label: 'Pathanamthitta', value: 'Pathanamthitta' },
    STT9QwPBvG1: { label: 'Pathankot', value: 'Pathankot' },
    SWGfjeTCzhn: { label: 'Pathology', value: 'Pathology' },
    Vc605OcQYge: { label: 'Patiala', value: 'Patiala' },
    tZGMiDCkGKs: { label: 'Patna', value: 'Patna' },
    sDknsnPntjw: { label: 'Pauri Garhwal', value: 'Pauri Garhwal' },
    xxAFLh9j40p: { label: 'Pediatric', value: 'Pediatric' },
    xxDnIbNDLyc: { label: 'Pediatric Medicine', value: 'Pediatric Medicine' },
    rurRwcCyiki: { label: 'Pediatric Oncology', value: 'Pediatric Oncology' },
    Pc8ITKTd7BG: {
        label: 'Pediatric Orthopedics',
        value: 'Pediatric Orthopedics',
    },
    QHZQiaJowsV: { label: 'Pediatric Surgery', value: 'Pediatric Surgery' },
    aXXkqTIeOsG: { label: 'pelliculosa', value: 'pelliculosa' },
    B3eDVqakfhs: { label: 'Perambalur', value: 'Perambalur' },
    vc4ALPDeeBI: { label: 'Peren', value: 'Peren' },
    jP4mIkjR2CW: { label: 'Pericardial fluid', value: 'Pericardial fluid' },
    Ydyw9IVRam8: {
        label: 'Peripheral catheter-blood',
        value: 'Peripheral catheter-blood',
    },
    M2Uiq7SplMs: { label: 'Peritoneal fluid', value: 'Peritoneal fluid' },
    zZbj4739i0m: { label: 'Pharmacology', value: 'Pharmacology' },
    MlizMT5GcOV: { label: 'Phek', value: 'Phek' },
    IoXUyxPPKhF: {
        label: 'Physical Medicine and Rehabilitation (PMR)',
        value: 'Physical Medicine and Rehabilitation (PMR)',
    },
    deI5YeLc1y4: { label: 'Physiology', value: 'Physiology' },
    XmvgvGSuNVM: { label: 'Pichia', value: 'Pichia' },
    nkKiyf32EAm: { label: 'Pichia fabianii', value: 'PIF' },
    tL2cNQUqmug: { label: 'Pichia jadinii', value: 'PIJ' },
    Xx5gNL8TQHH: { label: 'Pichia kudriavzevii', value: 'PIK' },
    hC4EQyQZHbx: { label: 'Pigtail fluid', value: 'Pigtail fluid' },
    ZymTV0B7MwT: { label: 'Pilibhit', value: 'Pilibhit' },
    tnpqvRfPKVl: { label: 'Pithoragarh', value: 'Pithoragarh' },
    t6sBVO1ttzz: { label: 'Placental Membrane', value: 'Placental Membrane' },
    ruu2cfFuODO: { label: 'Plastic surgery', value: 'Plastic surgery' },
    s5dFTQRVuxK: { label: 'Plesiomonas', value: 'Plesiomonas' },
    WtoY4WTnjy8: { label: 'Plesiomonas shigelloides', value: 'PSH' },
    ekIyGdT3f0T: { label: 'Plesiomonas shigelloides', value: 'PSH' },
    qdB84aJsYlO: { label: 'Pleural fluid', value: 'Pleural fluid' },
    hRH9q9krex0: { label: 'pneumoniae', value: 'pneumoniae' },
    s0Db0764XPD: { label: 'Pondicherry', value: 'Pondicherry' },
    sszwhBsq1Fm: { label: 'Poonch', value: 'Poonch' },
    S3FLxPoD9sb: { label: 'Porbandar', value: 'Porbandar' },
    m1sutxg74d5: { label: 'Positive', value: 'Positive' },
    fGIQfEOu0Ot: { label: 'Possible', value: 'Possible' },
    hGITcQ5GwLc: { label: 'PR-', value: 'Proteus sp.' },
    VMXm1gsDAy9: { label: 'Prakasam', value: 'Prakasam' },
    BlmoQcqAZg4: { label: 'Pratapgarh-R', value: 'Pratapgarh-R' },
    lcAVghMUldJ: { label: 'Pratapgarh-UP', value: 'Pratapgarh-UP' },
    A7etc1dSYJL: {
        label: 'Preventive and Social Medicine',
        value: 'Preventive and Social Medicine',
    },
    h6PbyZ3V6zn: { label: 'Proteomics', value: 'Proteomics' },
    E8U71xlAtjB: { label: 'Proteus', value: 'Proteus' },
    spjUnbWk4gB: { label: 'Proteus mirabilis', value: 'PMI' },
    k4VNSOIp2TW: { label: 'Proteus mirabilis', value: 'PMI' },
    zUuknWEnibR: { label: 'Proteus vulgaris', value: 'PVU' },
    dVxhqLI4nR6: { label: 'Proteus vulgaris', value: 'PVU' },
    KwGCHQjr4x4: { label: 'Providencia', value: 'Providencia' },
    beFueUCCJdD: { label: 'Providencia rettgeri', value: 'PRE' },
    wlwXVeMo8vm: { label: 'Providencia rettgeri', value: 'PRE' },
    sSgLoFfkNKc: { label: 'Providencia stuartii', value: 'PST' },
    SuG6WtVWOBq: { label: 'Providencia stuartii', value: 'PST' },
    Nb2f3khUIAD: { label: 'pseudointermedius', value: 'pseudointermedius' },
    uiDJwPGWh7S: { label: 'Pseudomonas', value: 'Pseudomonas' },
    JKd7nhGOOkj: { label: 'Pseudomonas aeruginosa', value: 'PAE' },
    dMMFHs6qgma: { label: 'Pseudomonas sp.', value: 'PS-' },
    yugmadkI5ll: { label: 'Pseudozyma', value: 'Pseudozyma' },
    tde0iSUbGvm: { label: 'Pseudozyma aphidis', value: 'PSA' },
    pDwpAfB433U: { label: 'Pseudozyma churashimaensis', value: 'PSC' },
    ZAitPc0vsir: { label: 'Psychiatry', value: 'Psychiatry' },
    GVI3WRm3XEN: { label: 'PTBD fluid', value: 'PTBD fluid' },
    iyWRnNkQVOJ: { label: 'Puducherry', value: 'Puducherry' },
    WR3b9FZsmuE: { label: 'Pudukkottai', value: 'Pudukkottai' },
    bMIRaXqhoJJ: { label: 'Pulmonary medicine', value: 'Pulmonary medicine' },
    E7RVyLeD4w0: { label: 'Pulmonology', value: 'Pulmonology' },
    q6tArQ8zynC: { label: 'Pulwama', value: 'Pulwama' },
    Bp2rYnMOQLt: { label: 'Pune', value: 'Pune' },
    BBOKSkbg4Z4: { label: 'Punjab', value: 'Punjab' },
    errMxJqvRlq: { label: 'Purba Bardhaman', value: 'Purba Bardhaman' },
    OfjpnbYJL3C: { label: 'Purba Medinipur', value: 'Purba Medinipur' },
    zfmsG91vLA4: { label: 'Pure', value: 'Pure' },
    AVq9WIfaVgB: { label: 'Puri', value: 'Puri' },
    Wo6MHGVYCZ8: { label: 'Purnia', value: 'Purnia' },
    Km12EP7iAtr: { label: 'Purulia', value: 'Purulia' },
    y31l83vkfdE: { label: 'Pus aspirate', value: 'Pus aspirate' },
    pgHOqR8BBLG: { label: 'Pus/exudate', value: 'Pus/exudate' },
    qvp01C5B1lf: { label: 'pyogenes', value: 'pyogenes' },
    YyqGOmbuCPy: { label: 'Radio diagnosis', value: 'Radio diagnosis' },
    zxzt8A7U9ZY: { label: 'Radiotherapy', value: 'Radiotherapy' },
    GCwWZTneaeG: { label: 'Raebareli', value: 'Raebareli' },
    w6Dn67RSdVi: { label: 'Raichur', value: 'Raichur' },
    k4Nc4GO23U9: { label: 'Raigad', value: 'Raigad' },
    idCYEXem2bL: { label: 'Raigarh', value: 'Raigarh' },
    zO6IprLUx7Z: { label: 'Raipur', value: 'Raipur' },
    PrJi1kODq7B: { label: 'Raisen', value: 'Raisen' },
    kOOwi8k3WIq: { label: 'Rajasthan', value: 'Rajasthan' },
    MyeErHg2htW: { label: 'Rajgarh', value: 'Rajgarh' },
    JaidhAC3TdS: { label: 'Rajkot', value: 'Rajkot' },
    c5zZ0OHYu14: { label: 'Rajnandgaon', value: 'Rajnandgaon' },
    qgtKyk4nRs6: { label: 'Rajouri', value: 'Rajouri' },
    XUTt5RlOPdU: { label: 'Rajsamand', value: 'Rajsamand' },
    f0VKxOPdIE9: { label: 'Ramanagara', value: 'Ramanagara' },
    X7wkI2QG60Y: { label: 'Ramanathapuram', value: 'Ramanathapuram' },
    y53NiUW5jrE: { label: 'Ramban', value: 'Ramban' },
    kw1pf6x8j33: { label: 'Ramgarh', value: 'Ramgarh' },
    G6LOHdni4Jz: { label: 'Rampur', value: 'Rampur' },
    gioS4gcNNwk: { label: 'Rampurhat HD', value: 'Rampurhat HD' },
    tL1CaDkiVTs: { label: 'Ranchi', value: 'Ranchi' },
    OEPIQSGtJkE: { label: 'Ranga Reddy', value: 'Ranga Reddy' },
    VBjmmqp2tSs: { label: 'Ratlam', value: 'Ratlam' },
    vf4mAs7erXH: { label: 'Ratnagiri', value: 'Ratnagiri' },
    a65DQiSp13s: { label: 'Rayagada', value: 'Rayagada' },
    hVSHdGFbcHE: { label: 'Reasi', value: 'Reasi' },
    Kxl9bpi3i0t: { label: 'Received', value: 'Received' },
    CRWvTedxUO8: { label: 'Reddiyarpalayam PHC', value: 'Reddiyarpalayam PHC' },
    ZWQIscpmtGo: { label: 'Rejected', value: 'Rejected' },
    jLYefJD9CLQ: { label: 'Renal transplant', value: 'Renal transplant' },
    uOniTbObj3o: {
        label: 'Reproductive medicine',
        value: 'Reproductive medicine',
    },
    l2pzbflZXvM: { label: 'Resend', value: 'Resend' },
    tDbWPG0mEYX: { label: 'Resistant', value: 'Resistant' },
    xXvn7D0SUX0: {
        label: 'Respiratory medicine',
        value: 'Respiratory medicine',
    },
    JF5bSazP3On: { label: 'rettgeri', value: 'rettgeri' },
    zg4BWXPsn2e: { label: 'Rewa', value: 'Rewa' },
    ynMfzw7UkML: { label: 'Rewari', value: 'Rewari' },
    WPicNI2EW14: { label: 'Rheumatology', value: 'Rheumatology' },
    HjYMmOsyBCn: { label: 'Rhizopus', value: 'Rhizopus' },
    QYdlUS7XsV0: { label: 'Rhizopus homothallicus', value: 'RHH' },
    BOcbRqBDu5X: { label: 'Rhizopus microsporus', value: 'RHM' },
    JFuAIVZLY9D: { label: 'Rhizopus oryzae', value: 'RHO' },
    UMCJPTFMTW2: { label: 'Rhodotorula', value: 'Rhodotorula' },
    pKIPL7rtYEa: { label: 'Rhodotorula glutinis', value: 'RGL' },
    KQA8SwsKIai: { label: 'Rhodotorula mucilaginosa', value: 'RRU' },
    sskbwFqHZ6t: { label: 'Ri Bhoi', value: 'Ri Bhoi' },
    ASZ7HJl94lF: { label: 'Rohtak', value: 'Rohtak' },
    EghMgbz22fz: { label: 'Rohtas', value: 'Rohtas' },
    DTUFEoSPtYx: { label: 'Ropar', value: 'Ropar' },
    xxRkjuCGlxT: { label: 'Rudraprayag', value: 'Rudraprayag' },
    DLDsZ4iOs48: { label: 'rugosa', value: 'rugosa' },
    I2HNbgFPMzF: { label: 'Rupnagar', value: 'Rupnagar' },
    JD4fpNciXg3: { label: 'Rural', value: 'Rural' },
    KX7l4cjuZHI: {
        label: 'Rural Unit for Health and Social Affairs (RUHSA)',
        value: 'Rural Unit for Health and Social Affairs (RUHSA)',
    },
    PdXn1Jlu9ls: { label: 'Sabarkantha', value: 'Sabarkantha' },
    UkoXiruD4Vw: { label: 'Saccharomyces', value: 'Saccharomyces' },
    p8rFR4qtPYH: { label: 'Saccharomyces cerevisiae', value: 'SCE' },
    MTUaX5ElhRB: { label: 'Sagar', value: 'Sagar' },
    JAw6LthNpM9: { label: 'Saharanpur', value: 'Saharanpur' },
    Is7SlIQphPn: { label: 'Saharsa', value: 'Saharsa' },
    R7SkBFdBSBH: { label: 'Sahibganj', value: 'Sahibganj' },
    nDNp5TS3e6k: {
        label: 'Sahibzada Ajit Singh Nagar',
        value: 'Sahibzada Ajit Singh Nagar',
    },
    cUg2KQROd9r: { label: 'Saiha', value: 'Saiha' },
    aM08x19Ip3M: { label: 'Salem', value: 'Salem' },
    YcDJyqRLkat: { label: 'Salmonella', value: 'Salmonella' },
    YrAbAgwHlWt: { label: 'Salmonella Enteritidis', value: 'SEN' },
    VOg7rJFoLvF: { label: 'Salmonella Heidelberg', value: 'SHG' },
    kZEMD0UCM6s: { label: 'Salmonella Newport', value: 'SNE' },
    locABQSKuvk: { label: 'Salmonella Paratyphi A', value: 'SAA' },
    ZxWAKAsOrk4: { label: 'Salmonella spp.', value: 'SAL' },
    aD1HCjrH0cb: { label: 'Salmonella spp. Faecal', value: 'SAF' },
    Cdf1MnYewRo: { label: 'Salmonella Typhi', value: 'SAT' },
    g9wB9GKKnIH: { label: 'Salmonella Typhimurium Faecal', value: 'STM' },
    XMVc2Gc8TQv: { label: 'Samastipur', value: 'Samastipur' },
    Ns3knvXfLZF: { label: 'Samba', value: 'Samba' },
    Aq2uewdvL5F: { label: 'Sambalpur', value: 'Sambalpur' },
    aiefNm5yzhv: {
        label: 'Sambhal(Bheem Nagar)',
        value: 'Sambhal(Bheem Nagar)',
    },
    VOU2yC5dzJq: { label: 'Sangli', value: 'Sangli' },
    YDasoSzHX3L: { label: 'Sangrur', value: 'Sangrur' },
    qwHPHq4DnTj: { label: 'Sant Kabir Nagar', value: 'Sant Kabir Nagar' },
    uhjk9wiRFlh: { label: 'Sant Ravidas Nagar', value: 'Sant Ravidas Nagar' },
    l5HTIEg4WOT: { label: 'saprophyticus', value: 'saprophyticus' },
    G3ibDDN6mhb: { label: 'Saran', value: 'Saran' },
    sGMEJxH6FGI: { label: 'Satara', value: 'Satara' },
    EEVWBQ4Yzip: { label: 'Satna', value: 'Satna' },
    q8f585vQzaR: { label: 'Sawai Madhopur', value: 'Sawai Madhopur' },
    A5igSMhmBOC: { label: 'Sedarapet PHC', value: 'Sedarapet PHC' },
    wHtkh7ToHIh: { label: 'Sehore', value: 'Sehore' },
    s3AfPlENY7L: { label: 'Semen', value: 'Semen' },
    RpUtK7KJbNi: { label: 'Senapati', value: 'Senapati' },
    Yy0nfQjJtqo: { label: 'Seoni', value: 'Seoni' },
    ZfjmqF4snLk: { label: 'Sepahijala', value: 'Sepahijala' },
    lPoYT9KHIKx: { label: 'Seraikela Kharsawan', value: 'Seraikela Kharsawan' },
    FlS6XCbOEgC: { label: 'Serchhip', value: 'Serchhip' },
    hgSPVwP3oEj: { label: 'Serratia', value: 'Serratia' },
    gkCAI3PDcB1: { label: 'Serratia marcescens', value: 'SMA' },
    ajklSjgS6mz: { label: 'SFM', value: 'SFM' },
    MVMrMkagJnF: { label: 'Shahdara', value: 'Shahdara' },
    WnpFwhuFZYM: { label: 'Shahdol', value: 'Shahdol' },
    NDOT7vsxHLB: {
        label: 'Shahid Bhagat Singh Nagar',
        value: 'Shahid Bhagat Singh Nagar',
    },
    LLbogbaiNUG: { label: 'Shahjahanpur', value: 'Shahjahanpur' },
    kXphKLTOiSg: { label: 'Shajapur', value: 'Shajapur' },
    OE3reL3maVx: { label: 'Shamli', value: 'Shamli' },
    DPTW0CunTyQ: { label: 'Sheikhpura', value: 'Sheikhpura' },
    rIiT4AIkhMJ: { label: 'Sheohar', value: 'Sheohar' },
    l50XFAdBNJg: { label: 'Sheopur', value: 'Sheopur' },
    nOwcpGBAY1D: { label: 'Shigella', value: 'Shigella' },
    YDQhsGjpKqI: { label: 'Shigella boydii', value: 'SHC' },
    IW3zmE6mapv: { label: 'Shigella dysenteriae', value: 'SHA' },
    QdWIdh4MnKN: { label: 'Shigella flexneri', value: 'SHB' },
    ZMufTGZDV4Q: { label: 'Shigella sonnei', value: 'SHD' },
    uJrtgeieHZu: { label: 'Shigella spp.', value: 'SHI' },
    bcGG04GJ6c2: { label: 'shigelloides', value: 'shigelloides' },
    CbepEx5Z3Dw: { label: 'Shimla', value: 'Shimla' },
    dHOhqFbai3D: { label: 'Shimoga', value: 'Shimoga' },
    nrFfWR1weYK: { label: 'Shivpuri', value: 'Shivpuri' },
    HkrqXitEOST: { label: 'Shopian', value: 'Shopian' },
    vpTBk5uvtMH: { label: 'Shravasti', value: 'Shravasti' },
    XBdbXCchzni: { label: 'Siddharthnagar', value: 'Siddharthnagar' },
    mCWZL0tBTF2: { label: 'Sidhi', value: 'Sidhi' },
    DeTgKqmdE1B: { label: 'Sikar', value: 'Sikar' },
    RyyJlu6mSZN: { label: 'Sikkim', value: 'Sikkim' },
    VHMlnflp7rc: { label: 'Simdega', value: 'Simdega' },
    IW4FD7UazXg: { label: 'Sindhudurg', value: 'Sindhudurg' },
    h262cLcdtxR: { label: 'Singrauli', value: 'Singrauli' },
    nGFtQkH7evJ: { label: 'Sinus mass', value: 'Sinus mass' },
    gdyB9IZOQiq: { label: 'Sirmaur', value: 'Sirmaur' },
    ua69N1DAbCR: { label: 'Sirohi', value: 'Sirohi' },
    QTKhIyit9JW: { label: 'Sirsa', value: 'Sirsa' },
    PXT8tGiguwq: { label: 'Sitamarhi', value: 'Sitamarhi' },
    Pg4v18o4Y7J: { label: 'Sitapur', value: 'Sitapur' },
    nsS4cixCvit: { label: 'Sivaganga', value: 'Sivaganga' },
    z1olYttfwDS: { label: 'Sivasagar', value: 'Sivasagar' },
    wh0jRGmHgxM: { label: 'Siwan', value: 'Siwan' },
    KqxpyVQJSVo: {
        label: 'Skin and Soft Tissue',
        value: 'Skin and Soft Tissue',
    },
    GuBcdbC02NG: { label: 'Skin biopsy', value: 'Skin biopsy' },
    gfLRdUVf8rC: { label: 'Solan', value: 'Solan' },
    bjN5CzTlDmZ: { label: 'Solapur', value: 'Solapur' },
    iNlhbE8E3UP: { label: 'Sonbhadra', value: 'Sonbhadra' },
    EAqpwxfxdCe: { label: 'Sonipat', value: 'Sonipat' },
    ZftZeAZHydV: { label: 'Sonitpur', value: 'Sonitpur' },
    AZl0IO8XqyI: { label: 'sonnei', value: 'sonnei' },
    HCogEn1r8Y8: { label: 'Sooramangalam PHC', value: 'Sooramangalam PHC' },
    E1zATbA0iMD: { label: 'Sorapet PHC', value: 'Sorapet PHC' },
    sAyLayhY0Pr: { label: 'South 24 Parganas', value: 'South 24 Parganas' },
    p7m7vRD90wY: { label: 'South Andaman', value: 'South Andaman' },
    i7RgHkoYney: { label: 'South Delhi', value: 'South Delhi' },
    zIQSu1dMtoJ: { label: 'South East Delhi', value: 'South East Delhi' },
    z7DSuiMuxYW: { label: 'South Garo Hills', value: 'South Garo Hills' },
    W9vBxUWtps8: { label: 'South Goa', value: 'South Goa' },
    UFEbuy8MNrM: { label: 'South Sikkim', value: 'South Sikkim' },
    OwfJ5MKi9Bx: { label: 'South Tripura', value: 'South Tripura' },
    e1lonbOW0DP: { label: 'South West Delhi', value: 'South West Delhi' },
    MvN1431oIUG: {
        label: 'South West Garo Hills',
        value: 'South West Garo Hills',
    },
    isv32Ln3jaY: {
        label: 'South West Khasi Hills',
        value: 'South West Khasi Hills',
    },
    GmuE6W6tBaL: { label: 'Special clinic', value: 'Special clinic' },
    OSubrzwYJMq: { label: 'spp.', value: 'spp.' },
    kDKd236bq9b: { label: 'Sputum', value: 'Sputum' },
    pMh0L9mHbDz: { label: 'SRGA', value: 'SRGA' },
    k3Et91tssig: { label: 'Srikakulam', value: 'Srikakulam' },
    GnvFQUspAkX: { label: 'Sri Muktsar Sahib', value: 'Sri Muktsar Sahib' },
    aFZ9saMwaeR: { label: 'Srinagar', value: 'Srinagar' },
    uFCRAiZv0N4: {
        label: 'Sri Potti Sriramulu Nellore',
        value: 'Sri Potti Sriramulu Nellore',
    },
    aBLpE1Kr78Q: {
        label: 'Staff student health service',
        value: 'Staff student health service',
    },
    Nz9nvemlg0I: { label: 'Staphylococcus', value: 'Staphylococcus' },
    y1oDLlQgWnb: { label: 'Staphylococcus aureus', value: 'SAU' },
    waSkwQt88zC: { label: 'Staphylococcus, coagulase negative', value: 'SCN' },
    amH9TTmF06b: { label: 'Staphylococcus epidermidis', value: 'SEP' },
    SeVLwgbNfBD: { label: 'Staphylococcus haemolyticus', value: 'SHL' },
    ereIkvpja1i: { label: 'Staphylococcus hominis', value: 'SHO' },
    JBN6R0GsfYM: { label: 'Staphylococcus lugdunensis', value: 'SLU' },
    kkNoEwyEb5m: { label: 'Staphylococcus pseudointermedius', value: 'SPE' },
    jWUwpAXN9lF: { label: 'Staphylococcus saprophyticus', value: 'SAP' },
    wYoFFKvKv6a: { label: 'Staphylococcus spp.', value: 'STA' },
    rCXqqpOWM5i: { label: 'Stenotrophomonas', value: 'Stenotrophomonas' },
    comfCdhCDhv: { label: 'Stenotrophomonas maltophilia', value: 'PMA' },
    iEBxM98T6us: { label: 'Streptococcus', value: 'Streptococcus' },
    ddfuvpamNxh: {
        label: 'Streptococcus, Group D (non-enterococcal)',
        value: 'DXE',
    },
    WlSwWq4M4o5: { label: 'Streptococcus pyogenes', value: 'SPY' },
    LUDTw0eBYRn: { label: 'stuartii', value: 'stuartii' },
    OwTkrcNiTio: {
        label: 'Subarnapur (Sonepur)',
        value: 'Subarnapur (Sonepur)',
    },
    uuTH4ARn8rT: { label: 'Sukma', value: 'Sukma' },
    f1io6P2B4lc: { label: 'Sultanpur', value: 'Sultanpur' },
    RnNQOSM7lY5: { label: 'Sundargarh', value: 'Sundargarh' },
    ZDUMq8jbSsC: { label: 'Supaul', value: 'Supaul' },
    io3cyIRE53M: { label: 'Superficial Biopsy', value: 'Superficial Biopsy' },
    VYjC9ZFx0md: { label: 'Superficial Tissue', value: 'Superficial Tissue' },
    rI7RtlTueTh: { label: 'Surajpur', value: 'Surajpur' },
    IA8qIRNxQjt: { label: 'Surat', value: 'Surat' },
    XQVZ4aojVPm: { label: 'Surendranagar', value: 'Surendranagar' },
    xm270IQjWt8: { label: 'Surgery', value: 'Surgery' },
    K7EgzupArfA: {
        label: 'Surgical Gastroenterology',
        value: 'Surgical Gastroenterology',
    },
    QFy2jr6W9sE: { label: 'Surgical Oncology', value: 'Surgical Oncology' },
    WiwZcwBfjL0: { label: 'Surguja', value: 'Surguja' },
    fS0YJtSVVJG: { label: 'Susceptible', value: 'Susceptible' },
    YwTAj5dg7p7: { label: 'Tamenglong', value: 'Tamenglong' },
    E0fTis1Bshm: { label: 'Tamil Nadu', value: 'Tamil Nadu' },
    OoIFY2Nb6fz: { label: 'Tapi', value: 'Tapi' },
    ztS5sDjlAfe: { label: 'Tarn Taran', value: 'Tarn Taran' },
    Jd9ih5zb0AD: { label: 'Tawang', value: 'Tawang' },
    z3xjwD6Nbu3: { label: 'Tehri Garhwal', value: 'Tehri Garhwal' },
    p9hpVNk1rK5: { label: 'Telangana', value: 'Telangana' },
    VIeEeRzsTog: { label: 'terreus', value: 'terreus' },
    Z3tG7yljFNy: { label: 'Thane', value: 'Thane' },
    d7QpERZxCCM: { label: 'Thanjavur', value: 'Thanjavur' },
    MYfwhNJ3dpg: { label: 'Thavalkuppam PHC', value: 'Thavalkuppam PHC' },
    dDuhkF89icZ: { label: 'Theni', value: 'Theni' },
    EiZ50hsjV8b: { label: 'Thirubuvanai PHC', value: 'Thirubuvanai PHC' },
    NyBbQopT1G9: { label: 'Thirukkanur PHC', value: 'Thirukkanur PHC' },
    GPgqWxDgKcM: { label: 'Thiruvananthapuram', value: 'Thiruvananthapuram' },
    BTDROhmqZJG: { label: 'Thoothukudi', value: 'Thoothukudi' },
    iRZnZimGYAD: { label: 'Thoubal', value: 'Thoubal' },
    fiwExaG0zAA: { label: 'Thrissur', value: 'Thrissur' },
    F1vgDYveoeM: { label: 'Throat swab', value: 'Throat swab' },
    hMWHN65SifT: { label: 'Tikamgarh', value: 'Tikamgarh' },
    tszmbRLVOHm: { label: 'Tinsukia', value: 'Tinsukia' },
    sVd7ZXc9NOL: { label: 'Tirap', value: 'Tirap' },
    YQ4BTWBvruz: { label: 'Tiruchirappalli', value: 'Tiruchirappalli' },
    Jz2LhHboj03: { label: 'Tirunelveli', value: 'Tirunelveli' },
    v8WMXUl2ijt: { label: 'Tirupur', value: 'Tirupur' },
    rYEQN95e0hD: { label: 'Tiruvallur', value: 'Tiruvallur' },
    k82HoYXrCQk: { label: 'Tiruvannamalai', value: 'Tiruvannamalai' },
    Ae6lBxYFGUg: { label: 'Tiruvarur', value: 'Tiruvarur' },
    sMZBfdZarIT: { label: 'Tonk', value: 'Tonk' },
    ZMP8WM1L3Ez: {
        label: 'Transfusion Medicine',
        value: 'Transfusion Medicine',
    },
    sICl0FPU103: { label: 'Transgender', value: 'Transgender' },
    JAzQXypyWXN: { label: 'Trichophyton', value: 'Trichophyton' },
    FNmKTJcNtIH: { label: 'Trichophyton mentagrophytes', value: 'TME' },
    iYQSO7cHygi: { label: 'Trichosporon', value: 'Trichosporon' },
    H6FPUxa5eG4: { label: 'Trichosporon asahii', value: 'TAS' },
    Ymjwld60PNf: { label: 'Trichosporon mucoides', value: 'TMU' },
    abtEmEtMPjj: { label: 'Tripura', value: 'Tripura' },
    olYnXy98Pxj: { label: 'tropicalis', value: 'tropicalis' },
    ZxTvHmxCSIH: { label: 'Truma unit', value: 'Truma unit' },
    cFcUhGF1eQ5: { label: 'Tuensang', value: 'Tuensang' },
    lmiDSuDBxVZ: { label: 'Tumkur', value: 'Tumkur' },
    stqGXNaUG9L: { label: 'Typhi', value: 'Typhi' },
    ZqVQThvYx7D: { label: 'Typhimurium', value: 'Typhimurium' },
    NleAmYVDKRx: { label: 'Udaipur', value: 'Udaipur' },
    ZhDZzx6l4yM: { label: 'Udalguri', value: 'Udalguri' },
    r9QnJZiIPfo: { label: 'Udhampur', value: 'Udhampur' },
    TXkKB3RKOCy: { label: 'Udham Singh Nagar', value: 'Udham Singh Nagar' },
    zm4iObrfseW: { label: 'Udupi', value: 'Udupi' },
    Ni4w86pPhro: { label: 'Ujjain', value: 'Ujjain' },
    IHgXVTquA8I: { label: 'Ukhrul', value: 'Ukhrul' },
    zQsw9CUC9TB: { label: 'Umaria', value: 'Umaria' },
    rlRxOu2jHrF: { label: 'Una', value: 'Una' },
    HO3IJsQ7NVI: { label: 'Unnao', value: 'Unnao' },
    phq4AyXUXlN: { label: 'Unokoti', value: 'Unokoti' },
    sQXupOopA96: { label: 'Upper Siang', value: 'Upper Siang' },
    Roa5h2rOiU7: { label: 'Upper Subansiri', value: 'Upper Subansiri' },
    eFLKHHq12y9: { label: 'Urban', value: 'Urban' },
    EGmOA9IMnqU: { label: 'Urinary catheter', value: 'Urinary catheter' },
    KFtI4EvFofH: { label: 'Urine', value: 'Urine' },
    B0xfkc7AHiD: { label: 'Urological Oncology', value: 'Urological Oncology' },
    yKSHte5hU0U: { label: 'Urology', value: 'Urology' },
    NYm39cljfqS: { label: 'utilis', value: 'utilis' },
    XMOVEno9r5M: { label: 'Uttara Kannada', value: 'Uttara Kannada' },
    bCvUYcHT5nh: { label: 'Uttarakhand', value: 'Uttarakhand' },
    MbbJMcUpnGi: { label: 'Uttar Dinajpur', value: 'Uttar Dinajpur' },
    I7C7Rmhgs90: { label: 'Uttarkashi', value: 'Uttarkashi' },
    WDlGoLf6miN: { label: 'Uttar Pradesh', value: 'Uttar Pradesh' },
    dAIWCLtf0Hp: { label: 'Vadodara', value: 'Vadodara' },
    NBpTHUK7gIh: { label: 'Vaginal swab', value: 'Vaginal swab' },
    LU8kFhpbzRI: { label: 'Vaishali', value: 'Vaishali' },
    bHaxFwJCmz9: { label: 'Valsad', value: 'Valsad' },
    Yc5clA11yui: { label: 'Varanasi', value: 'Varanasi' },
    yzG4l11bhLM: {
        label: 'Vascular Catheter tip',
        value: 'Vascular Catheter tip',
    },
    cYuafB4gNH1: { label: 'Vellore', value: 'Vellore' },
    BHT6EJpJcZ3: { label: 'versicolor', value: 'versicolor' },
    cg4UXthTvmx: { label: 'Vibrio', value: 'Vibrio' },
    Nmfb8S2JbiZ: { label: 'Vibrio cholerae', value: 'VIC' },
    c5N9TTk3t6R: { label: 'Vibrio parahaemolyticus', value: 'VIP' },
    ZDQm2tgr6pd: { label: 'Vibrio spp.', value: 'VI-' },
    D0sHrFmNEin: { label: 'Vidisha', value: 'Vidisha' },
    T6eoysELqWw: { label: 'Vijayapura', value: 'Vijayapura' },
    Q7BcFFAmPxq: { label: 'Villianur PHC', value: 'Villianur PHC' },
    I8X3QMkAsB7: { label: 'Viluppuram', value: 'Viluppuram' },
    s5Ait0W6MxY: { label: 'viridans', value: 'viridans' },
    kEIJsTp6EgG: { label: 'Virudhunagar', value: 'Virudhunagar' },
    lrGAMhKtkrD: { label: 'Visakhapatnam', value: 'Visakhapatnam' },
    EnRoNo2sHKe: { label: 'vishwanathii', value: 'vishwanathii' },
    VrAGW0t1cSR: { label: 'Vitreous fluid', value: 'Vitreous fluid' },
    Biw3KWQE3cp: { label: 'Vizianagaram', value: 'Vizianagaram' },
    IhoB1dPd0QF: { label: 'vulgaris', value: 'vulgaris' },
    nCKEZZOqABB: { label: 'Warangal', value: 'Warangal' },
    AJb375n8p20: { label: 'Ward', value: 'Ward' },
    Dw7uhe4A8Si: { label: 'Wardha', value: 'Wardha' },
    yapBXnyGNvU: { label: 'Ward (Non ICU)', value: 'Ward' },
    rojAdWFXjqV: { label: 'Washim', value: 'Washim' },
    kKZIh3ZkqUD: { label: 'Wayanad', value: 'Wayanad' },
    QA1eWAvooYs: { label: 'West Bengal', value: 'West Bengal' },
    m3X2zVhRYjG: { label: 'West Champaran', value: 'West Champaran' },
    X5uHtI8Uuk0: { label: 'West Delhi', value: 'West Delhi' },
    ocwMCkkCKcs: { label: 'West Garo Hills', value: 'West Garo Hills' },
    cZQ8YFeXUnn: { label: 'West Godavari', value: 'West Godavari' },
    UxBad8Ieg80: { label: 'West Kameng', value: 'West Kameng' },
    Yln9yubBtHM: { label: 'West Khasi Hills', value: 'West Khasi Hills' },
    sosggHCDg7j: { label: 'West Siang', value: 'West Siang' },
    ugSeoRsUfoN: { label: 'West Sikkim', value: 'West Sikkim' },
    F8fEClD2ScK: { label: 'West Singhbhum', value: 'West Singhbhum' },
    Pz6Ru4SYdPH: { label: 'West Tripura', value: 'West Tripura' },
    EHn0audjzWd: {
        label: 'Whole Genome Sequencing',
        value: 'Whole Genome Sequencing',
    },
    Ookod7dyrSF: { label: 'Wickeromyces', value: 'Wickeromyces' },
    vI4SPfEZJQ3: { label: 'Wokha', value: 'Wokha' },
    x6f6JCJ0A39: { label: 'Wound swab', value: 'Wound swab' },
    M4hgQ3B8E8X: { label: 'Yadgir', value: 'Yadgir' },
    ie5KjqABOxk: { label: 'Yamuna Nagar', value: 'Yamuna Nagar' },
    LjXLVVygnAB: { label: 'Yanam', value: 'Yanam' },
    RHS8NTEqCPu: { label: 'Yavatmal', value: 'Yavatmal' },
    RV2pEWV02Ig: { label: 'Yeast', value: 'YEA' },
    fOoT5eIUjhD: { label: 'Yersinia', value: 'Yersinia' },
    TOQAuEqYFfm: { label: 'Yersinia enterocolitica', value: 'YEN' },
    IxHa5eN3npv: { label: 'Zunheboto', value: 'Zunheboto' },
}
