export const programStageSections = [
    {
        name: 'Institute / Hospital Information',
        id: 'I3JompXVC8f',
        displayName: 'Institute / Hospital Information',
        renderType: {
            MOBILE: { type: 'LISTING' },
            DESKTOP: { type: 'LISTING' },
        },
        dataElements: [
            'dRKIjwIDab4',
            'B7XuDaXPv10',
            'DeFdBFxsFcj',
            'tQa6uU1t6s3',
            'YoCmEMUlZxb',
            'JRUa0qYKQDF',
        ],
        childSections: [
            {
                name: 'Comorbidity',
                id: 'SWgQtZi3Zl0',
                displayName: '{Institute / Hospital Information}Comorbidity',
                renderType: {
                    MOBILE: { type: 'LISTING' },
                    DESKTOP: { type: 'LISTING' },
                },
                dataElements: [
                    'nEfLWIBwOPB',
                    'zsFKZXUSiNW',
                    'baxKkJgSyII',
                    'V0C17jO5GqO',
                    'CqyqhAIuUSP',
                ],
                editable: false,
                childSections: [],
            },
            {
                name: 'Patient with devices',
                id: 'ipNzwmuaZl7',
                displayName:
                    '{Institute / Hospital Information}Patient with devices',
                renderType: {
                    MOBILE: { type: 'LISTING' },
                    DESKTOP: { type: 'LISTING' },
                },
                dataElements: [
                    'uZUkIz4DqZH',
                    'OHXVNBbvgDV',
                    'X9a03L4qiJH',
                    'eJ98ISBzwvG',
                    'tkanCVcePsh',
                    'h9RODgVF4O1',
                ],
                editable: false,
                childSections: [],
            },
        ],
    },
    {
        name: 'Sample information',
        id: 'ynJS0PWBkVv',
        displayName: 'Sample information',
        renderType: {
            MOBILE: { type: 'LISTING' },
            DESKTOP: { type: 'LISTING' },
        },
        dataElements: [
            'GpAu5HjWAEz',
            'mp5MeJ2dFQz',
            'lIkk661BLpG',
            'SaQe2REkGVw',
            'K8eNq7JZeUs',
        ],
        childSections: [
            {
                name:
                    'Antibiotics/Antifungals (Taken for 3 days in last 1 month)',
                id: 'nabhZ2PJwEC',
                displayName:
                    '{Sample information}Antibiotics/Antifungals (Taken for 3 days in last 1 month)',
                renderType: {
                    MOBILE: { type: 'LISTING' },
                    DESKTOP: { type: 'LISTING' },
                },
                dataElements: [
                    'RRc3et0yhsn',
                    'hVjlOYaCYMS',
                    'khMMIiU2Zwa',
                    'kH30plwbeAP',
                    'kAOxkp1lQdB',
                ],
                editable: false,
                childSections: [],
            },
        ],
    },
    {
        name: 'Susceptibility tests',
        id: 'FXEa445ynRz',
        displayName: 'Susceptibility tests',
        renderType: {
            MOBILE: { type: 'LISTING' },
            DESKTOP: { type: 'LISTING' },
        },
        dataElements: [],
        childSections: [
            {
                name: 'DD',
                id: 'lc3i0uOH16d',
                displayName: '{Susceptibility tests}DD',
                renderType: {
                    MOBILE: { type: 'LISTING' },
                    DESKTOP: { type: 'LISTING' },
                },
                dataElements: [
                    'VGdJnkTlNyK',
                    'SZJuj0AmGxB',
                    'lpWR8ZSa1zC',
                    'nikrSOx63ce',
                    'el3u1NbJxSg',
                    'tVIynZXmqls',
                    'fOmuusloF7k',
                    'E7EyQm7euHu',
                    'vX1XAmSKfxx',
                    'vRWArSA8urW',
                    'O6dwlDQhKUS',
                    'LX2UJgFtmhE',
                    'IvruNSGNqg7',
                    'Hp3PSM2svaM',
                ],
                editable: false,
                childSections: [],
            },
            {
                name: 'MIC',
                id: 'BR1u3ATtiAe',
                displayName: '{Susceptibility tests}MIC',
                renderType: {
                    MOBILE: { type: 'LISTING' },
                    DESKTOP: { type: 'LISTING' },
                },
                dataElements: [
                    'GYNpOJWcNx2',
                    'lQYcD2hTocV',
                    'uiMdxS6pvHt',
                    'f666SCFrjuM',
                    'DGZI26b22go',
                    'lL2LC94BTw3',
                    'PTbpw8gED1N',
                    'f0vYwlbsdQA',
                    'f3R5QjfaCMc',
                    'S5dYjuVXvgZ',
                    'U7nHovss4xK',
                    'j7Oenm7cXWx',
                    'dSu1B7lkeEM',
                ],
                editable: false,
                childSections: [],
            },
        ],
    },
    {
        name: 'Results',
        id: 'gIcsO2tvXcc',
        displayName: 'Results',
        renderType: {
            MOBILE: { type: 'LISTING' },
            DESKTOP: { type: 'LISTING' },
        },
        dataElements: [
            'KmgWX65h0iM',
            'AC3ZDhUyjDX',
            'cPYspBpRsuQ',
            'tapnaxXHuz5',
            'CrkSOhRJQbn',
            'obDZttfd7Cm',
            'mx4AYggTTir',
            'WpEHYngpFoy',
            'oGYzzGCDmze',
            'kQdkrguULKu',
            'heyrUXjYYcP',
            'cxZhnL2j4AX',
            'wcoEmlL4YNV',
        ],
        hideWithValues: true,
        childSections: [],
    },
    {
        name: 'Phenotypic tests',
        id: 'TffDV3HIA4Y',
        displayName: 'Phenotypic tests',
        renderType: {
            MOBILE: { type: 'LISTING' },
            DESKTOP: { type: 'MATRIX' },
        },
        dataElements: [
            'eGqo7EpSqhA',
            'eYLIi9qzRgz',
            'nVpNqeBuaHC',
            'oqziA8urxFq',
            'qwtAhlVyVCM',
        ],
        childSections: [],
    },
    {
        name: 'Genotypic tests',
        id: 'Qlq32vAadhQ',
        displayName: 'Genotypic tests',
        renderType: {
            MOBILE: { type: 'LISTING' },
            DESKTOP: { type: 'MATRIX' },
        },
        dataElements: [
            'n280itgv0pc',
            'el253B8KxIO',
            'ZMGTVgARAjB',
            'DN2gTLIY37z',
            'LA0aVW2YknF',
            'H7pX1NhU9b2',
            'KbzF1gX26kT',
            'PIlH8Hbkm02',
            'zj5YX1v02Xd',
            'PtRZ073XrxS',
            'FPMhfReDAqt',
            'TSVUS90Dvw6',
            'ezVuuGTMt4p',
            'tDskrlL66k3',
            'kHFQmnaSKZA',
            'QVUb8CY6OTX',
            'e6VZ8ga7uCi',
            'bfMusN9Jspz',
            'LKslj5qwCsY',
        ],
        childSections: [],
    },
    {
        name: 'Approval',
        id: 'uKKviTKyKLt',
        displayName: 'Approval',
        renderType: {
            MOBILE: { type: 'LISTING' },
            DESKTOP: { type: 'LISTING' },
        },
        dataElements: [],
        hideWithValues: true,
        childSections: [
            {
                name: 'Level 1',
                id: 'DHywWtrBcd4',
                displayName: '{Approval}Level 1',
                renderType: {
                    MOBILE: { type: 'LISTING' },
                    DESKTOP: { type: 'LISTING' },
                },
                dataElements: ['tAyVrNUTVHX', 'NLmLwjdSHMv', 'wCNQtIHJRON'],
                editable: false,
                childSections: [],
            },
            {
                name: 'Level 2',
                id: 'Q2ZP7Rn5vx0',
                displayName: '{Approval}Level 2',
                renderType: {
                    MOBILE: { type: 'LISTING' },
                    DESKTOP: { type: 'LISTING' },
                },
                dataElements: ['sXDQT6Yaf77', 'pz8SoHBO6RL', 'fEnFVvEFKVc'],
                editable: false,
                childSections: [],
                hide: true,
            },
        ],
    },
    {
        name: 'Isolate transfer',
        id: 'MSZCgLxDtNs',
        displayName: 'Isolate transfer',
        renderType: {
            MOBILE: { type: 'LISTING' },
            DESKTOP: { type: 'LISTING' },
        },
        dataElements: [
            'wNTllPkgB92',
            'nU2wf4hwlDD',
            'D4jwjr4opAv',
            'BQwb1YbN3mH',
            'KHHHMoiUsWZ',
            'H4s7FuoY3Hm',
            'hQmS69HXStI',
            'qNmtxrjYccb',
        ],
        hideWithValues: true,
        childSections: [],
    },
]
