export const dataElementsOutput = {
    dRKIjwIDab4: {
        required: true,
        hide: false,
        code: 'DEPARTMENT',
        id: 'dRKIjwIDab4',
        valueType: 'TEXT',
        displayFormName: 'Hospital department',
        optionSetValue: true,
        optionSet: 's1UF1wpUrpB',
    },
    B7XuDaXPv10: {
        required: true,
        hide: false,
        code: 'LOCATION',
        id: 'B7XuDaXPv10',
        valueType: 'TEXT',
        displayFormName: 'Location',
        optionSetValue: true,
        optionSet: 'Ann08p13CZQ',
    },
    DeFdBFxsFcj: {
        required: true,
        hide: false,
        code: 'INFECTION',
        id: 'DeFdBFxsFcj',
        valueType: 'TEXT',
        displayFormName: 'Type of infection',
        optionSetValue: true,
        optionSet: 'c5unlpfGaog',
    },
    tQa6uU1t6s3: {
        required: false,
        hide: false,
        code: 'Admission_history',
        id: 'tQa6uU1t6s3',
        valueType: 'TEXT',
        displayFormName: 'Admission_history',
        optionSetValue: true,
        optionSet: 'LJUDbVIHDgw',
    },
    JRUa0qYKQDF: {
        required: true,
        hide: false,
        id: 'JRUa0qYKQDF',
        valueType: 'DATE',
        displayFormName: 'OPD visit / Admission date',
        optionSetValue: false,
    },
    YoCmEMUlZxb: {
        required: false,
        hide: false,
        code: 'Diagnosis',
        id: 'YoCmEMUlZxb',
        valueType: 'TEXT',
        displayFormName: 'Clinical diagnosis',
        optionSetValue: false,
    },
    zsFKZXUSiNW: {
        required: false,
        hide: false,
        id: 'zsFKZXUSiNW',
        valueType: 'TRUE_ONLY',
        displayFormName: 'Comorbidity - Diabetes mellitus',
        optionSetValue: false,
    },
    nEfLWIBwOPB: {
        required: false,
        hide: false,
        id: 'nEfLWIBwOPB',
        valueType: 'TRUE_ONLY',
        displayFormName: 'Comorbidity - Malignancy',
        optionSetValue: false,
    },
    V0C17jO5GqO: {
        required: false,
        hide: false,
        id: 'V0C17jO5GqO',
        valueType: 'TRUE_ONLY',
        displayFormName: 'Comorbidity - Others',
        optionSetValue: false,
    },
    CqyqhAIuUSP: {
        required: false,
        hide: true,
        id: 'CqyqhAIuUSP',
        valueType: 'TEXT',
        displayFormName: 'Comorbidity - others - details',
        optionSetValue: false,
    },
    baxKkJgSyII: {
        required: false,
        hide: false,
        id: 'baxKkJgSyII',
        valueType: 'TRUE_ONLY',
        displayFormName: 'Comorbidity - Transplantation',
        optionSetValue: false,
    },
    h9RODgVF4O1: {
        required: false,
        hide: true,
        id: 'h9RODgVF4O1',
        valueType: 'TEXT',
        displayFormName: 'Devices - others',
        optionSetValue: false,
    },
    uZUkIz4DqZH: {
        required: false,
        hide: false,
        id: 'uZUkIz4DqZH',
        valueType: 'TRUE_ONLY',
        displayFormName: 'Devices - Endotracheal tube',
        optionSetValue: false,
    },
    OHXVNBbvgDV: {
        required: false,
        hide: false,
        id: 'OHXVNBbvgDV',
        valueType: 'TRUE_ONLY',
        displayFormName: 'Devices - Mechanical ventilator',
        optionSetValue: false,
    },
    eJ98ISBzwvG: {
        required: false,
        hide: false,
        id: 'eJ98ISBzwvG',
        valueType: 'TRUE_ONLY',
        displayFormName: 'Devices',
        optionSetValue: false,
    },
    X9a03L4qiJH: {
        required: false,
        hide: false,
        id: 'X9a03L4qiJH',
        valueType: 'TRUE_ONLY',
        displayFormName: 'Devices - Urinary catheter',
        optionSetValue: false,
    },
    tkanCVcePsh: {
        required: false,
        hide: false,
        id: 'tkanCVcePsh',
        valueType: 'TRUE_ONLY',
        displayFormName: 'Devices - Other vascular access lines',
        optionSetValue: false,
    },
    RRc3et0yhsn: {
        required: false,
        hide: false,
        id: 'RRc3et0yhsn',
        valueType: 'TEXT',
        displayFormName: 'History of Antibiotics / Antifungals - 1',
        optionSetValue: false,
    },
    hVjlOYaCYMS: {
        required: false,
        hide: true,
        id: 'hVjlOYaCYMS',
        valueType: 'TEXT',
        displayFormName: 'History of Antibiotics / Antifungals - 2',
        optionSetValue: false,
    },
    khMMIiU2Zwa: {
        required: false,
        hide: true,
        id: 'khMMIiU2Zwa',
        valueType: 'TEXT',
        displayFormName: 'History of Antibiotics / Antifungals - 3',
        optionSetValue: false,
    },
    kH30plwbeAP: {
        required: false,
        hide: true,
        id: 'kH30plwbeAP',
        valueType: 'TEXT',
        displayFormName: 'History of Antibiotics / Antifungals - 4',
        optionSetValue: false,
    },
    kAOxkp1lQdB: {
        required: false,
        hide: true,
        id: 'kAOxkp1lQdB',
        valueType: 'TEXT',
        displayFormName: 'History of Antibiotics / Antifungals - 5',
        optionSetValue: false,
    },
    GpAu5HjWAEz: {
        required: true,
        hide: false,
        code: 'LAB_ID',
        id: 'GpAu5HjWAEz',
        valueType: 'TEXT',
        displayFormName: 'Lab Sample ID',
        optionSetValue: false,
    },
    mp5MeJ2dFQz: {
        required: true,
        hide: false,
        code: 'SAMPLE_TYPE',
        id: 'mp5MeJ2dFQz',
        valueType: 'TEXT',
        displayFormName: 'Sample type',
        optionSetValue: true,
        optionSet: 'ZAZ0x81n1G6',
    },
    lIkk661BLpG: {
        required: false,
        hide: false,
        code: 'AMR Id',
        id: 'lIkk661BLpG',
        valueType: 'TEXT',
        displayFormName: 'AMR ID',
        optionSetValue: false,
        disabled: true,
    },
    SaQe2REkGVw: {
        required: true,
        hide: false,
        hideWithValues: true,
        code: 'ORGANISM',
        id: 'SaQe2REkGVw',
        valueType: 'TEXT',
        displayFormName: 'Organism',
        optionSetValue: true,
        optionSet: 's7YngGChrdh',
        disabled: true,
    },
    K8eNq7JZeUs: {
        required: true,
        hide: false,
        code: 'IDENTIFICATION',
        id: 'K8eNq7JZeUs',
        valueType: 'TEXT',
        displayFormName: 'Identification Method',
        optionSetValue: true,
        optionSet: 'W6VW2cKU8Jf',
    },
    GYNpOJWcNx2: {
        required: false,
        hide: false,
        id: 'GYNpOJWcNx2',
        valueType: 'NUMBER',
        displayFormName: 'Amikacin_MIC_CLSI_Human',
        optionSetValue: false,
        color: '',
        warning: '',
    },
    VGdJnkTlNyK: {
        required: false,
        hide: false,
        code: 'AMK_ND30',
        id: 'VGdJnkTlNyK',
        valueType: 'NUMBER',
        displayFormName: 'Amikacin_Disk diffusion_CLSI_30_Human',
        optionSetValue: false,
        color: 'red',
        warning: '',
    },
    KmgWX65h0iM: {
        required: false,
        hide: false,
        id: 'KmgWX65h0iM',
        valueType: 'TEXT',
        displayFormName: 'Amikacin_Result',
        optionSetValue: true,
        optionSet: 'bSgpKbkbVGL',
        disabled: true,
    },
    lpWR8ZSa1zC: {
        required: false,
        hide: false,
        code: 'CTX_ND30',
        id: 'lpWR8ZSa1zC',
        valueType: 'NUMBER',
        displayFormName: 'Cefotaxime_Disk diffusion_CLSI_30_Human',
        optionSetValue: false,
        color: '',
        warning: '',
    },
    uiMdxS6pvHt: {
        required: false,
        hide: false,
        code: 'CTX_NM',
        id: 'uiMdxS6pvHt',
        valueType: 'NUMBER',
        displayFormName: 'Cefotaxime_MIC_CLSI_Human',
        optionSetValue: false,
        color: '',
        warning: '',
    },
    cPYspBpRsuQ: {
        required: false,
        hide: true,
        id: 'cPYspBpRsuQ',
        valueType: 'TEXT',
        displayFormName: 'Cefotaxime_Result',
        optionSetValue: true,
        optionSet: 'bSgpKbkbVGL',
    },
    nikrSOx63ce: {
        required: false,
        hide: false,
        code: 'CIP_ND5',
        id: 'nikrSOx63ce',
        valueType: 'NUMBER',
        displayFormName: 'Ciprofloxacin_Disk diffusion_CLSI_5_Human',
        optionSetValue: false,
        color: '',
        warning: '',
    },
    f666SCFrjuM: {
        required: false,
        hide: false,
        id: 'f666SCFrjuM',
        valueType: 'NUMBER',
        displayFormName: 'Ciprofloxacin_MIC_CLSI_Human',
        optionSetValue: false,
        color: '',
        warning: '',
    },
    tapnaxXHuz5: {
        required: false,
        hide: true,
        id: 'tapnaxXHuz5',
        valueType: 'TEXT',
        displayFormName: 'Ciprofloxacin_Result',
        optionSetValue: true,
        optionSet: 'bSgpKbkbVGL',
    },
    obDZttfd7Cm: {
        required: false,
        hide: true,
        id: 'obDZttfd7Cm',
        valueType: 'TEXT',
        displayFormName: 'Ertapenem_Result',
        optionSetValue: true,
        optionSet: 'bSgpKbkbVGL',
    },
    el3u1NbJxSg: {
        required: false,
        hide: false,
        id: 'el3u1NbJxSg',
        valueType: 'NUMBER',
        displayFormName: 'Ertapenem_Disk diffusion_CLSI_10_Human',
        optionSetValue: false,
        color: '',
        warning: '',
    },
    lL2LC94BTw3: {
        required: false,
        hide: false,
        id: 'lL2LC94BTw3',
        valueType: 'NUMBER',
        displayFormName: 'Ertapenem_MIC_CLSI_Human',
        optionSetValue: false,
        color: '',
        warning: '',
    },
    fOmuusloF7k: {
        required: false,
        hide: false,
        code: 'IPM_ND10',
        id: 'fOmuusloF7k',
        valueType: 'NUMBER',
        displayFormName: 'Imipenem_Disk diffusion_CLSI_10_Human',
        optionSetValue: false,
        color: '',
        warning: '',
    },
    f0vYwlbsdQA: {
        required: false,
        hide: false,
        id: 'f0vYwlbsdQA',
        valueType: 'NUMBER',
        displayFormName: 'Imipenem_MIC_CLSI_Human',
        optionSetValue: false,
        color: '',
        warning: '',
    },
    WpEHYngpFoy: {
        required: false,
        hide: true,
        id: 'WpEHYngpFoy',
        valueType: 'TEXT',
        displayFormName: 'Imipenem_Result',
        optionSetValue: true,
        optionSet: 'bSgpKbkbVGL',
    },
    S5dYjuVXvgZ: {
        required: false,
        hide: false,
        id: 'S5dYjuVXvgZ',
        valueType: 'NUMBER',
        displayFormName: 'Meropenem_MIC_CLSI_Human',
        optionSetValue: false,
        color: '',
        warning: '',
    },
    vX1XAmSKfxx: {
        required: false,
        hide: false,
        id: 'vX1XAmSKfxx',
        valueType: 'NUMBER',
        displayFormName: 'Meropenem_Disk diffusion_CLSI_10_Human',
        optionSetValue: false,
        color: '',
        warning: '',
    },
    kQdkrguULKu: {
        required: false,
        hide: true,
        id: 'kQdkrguULKu',
        valueType: 'TEXT',
        displayFormName: 'Meropenem_Result',
        optionSetValue: true,
        optionSet: 'bSgpKbkbVGL',
    },
    vRWArSA8urW: {
        required: false,
        hide: false,
        code: 'NIT_ND',
        id: 'vRWArSA8urW',
        valueType: 'NUMBER',
        displayFormName: 'Nitrofurantoin_Disk diffusion_CLSI_300_Human',
        optionSetValue: false,
        color: '',
        warning: '',
    },
    U7nHovss4xK: {
        required: false,
        hide: false,
        id: 'U7nHovss4xK',
        valueType: 'NUMBER',
        displayFormName: 'Nitrofurantoin_MIC_CLSI_Human',
        optionSetValue: false,
        color: '',
        warning: '',
    },
    heyrUXjYYcP: {
        required: false,
        hide: true,
        id: 'heyrUXjYYcP',
        valueType: 'TEXT',
        displayFormName: 'Nitrofurantoin_Result',
        optionSetValue: true,
        optionSet: 'bSgpKbkbVGL',
    },
    O6dwlDQhKUS: {
        required: false,
        hide: false,
        code: 'PIP_ND100',
        id: 'O6dwlDQhKUS',
        valueType: 'NUMBER',
        displayFormName:
            'Piperacillin-tazobactam_Disk diffusion_CLSI_100_Human',
        optionSetValue: false,
        color: '',
        warning: '',
    },
    LX2UJgFtmhE: {
        required: false,
        hide: false,
        id: 'LX2UJgFtmhE',
        valueType: 'NUMBER',
        displayFormName: 'Piperacillin-tazobactam_Disk diffusion_CLSI_10_Human',
        optionSetValue: false,
        color: '',
        warning: '',
    },
    j7Oenm7cXWx: {
        required: false,
        hide: false,
        id: 'j7Oenm7cXWx',
        valueType: 'NUMBER',
        displayFormName: 'Piperacillin-tazobactam_MIC_CLSI_Human',
        optionSetValue: false,
        color: '',
        warning: '',
    },
    cxZhnL2j4AX: {
        required: false,
        hide: true,
        id: 'cxZhnL2j4AX',
        valueType: 'TEXT',
        displayFormName: 'Piperacillin-tazobactam_Result',
        optionSetValue: true,
        optionSet: 'bSgpKbkbVGL',
    },
    IvruNSGNqg7: {
        required: false,
        hide: false,
        code: 'SXT_ND1_2',
        id: 'IvruNSGNqg7',
        valueType: 'NUMBER',
        displayFormName:
            'Trimethoprim-sulfamethoxazole_Disk diffusion_CLSI_1.25_Human',
        optionSetValue: false,
        color: '',
        warning: '',
    },
    Hp3PSM2svaM: {
        required: false,
        hide: false,
        id: 'Hp3PSM2svaM',
        valueType: 'NUMBER',
        displayFormName:
            'Trimethoprim-sulfamethoxazole_Disk diffusion_CLSI_23.75_Human',
        optionSetValue: false,
        color: '',
        warning: '',
    },
    dSu1B7lkeEM: {
        required: false,
        hide: false,
        id: 'dSu1B7lkeEM',
        valueType: 'NUMBER',
        displayFormName: 'Trimethoprim-sulfamethoxazole_MIC_CLSI_Human',
        optionSetValue: false,
        color: '',
        warning: '',
    },
    wcoEmlL4YNV: {
        required: false,
        hide: true,
        id: 'wcoEmlL4YNV',
        valueType: 'TEXT',
        displayFormName: 'Trimethoprim-sulfamethoxazole_Result',
        optionSetValue: true,
        optionSet: 'bSgpKbkbVGL',
    },
    E7EyQm7euHu: {
        required: false,
        hide: false,
        id: 'E7EyQm7euHu',
        valueType: 'NUMBER',
        displayFormName: 'Levofloxacin_Disk diffusion_CLSI_5_Human',
        optionSetValue: false,
        color: '',
        warning: '',
    },
    f3R5QjfaCMc: {
        required: false,
        hide: false,
        id: 'f3R5QjfaCMc',
        valueType: 'NUMBER',
        displayFormName: 'Levofloxacin_MIC_CLSI_Human',
        optionSetValue: false,
        color: '',
        warning: '',
    },
    oGYzzGCDmze: {
        required: false,
        hide: true,
        id: 'oGYzzGCDmze',
        valueType: 'TEXT',
        displayFormName: 'Levofloxacin_Result',
        optionSetValue: true,
        optionSet: 'bSgpKbkbVGL',
    },
    SZJuj0AmGxB: {
        required: false,
        hide: false,
        id: 'SZJuj0AmGxB',
        valueType: 'NUMBER',
        displayFormName: 'Cefazolin_Disk diffusion_CLSI_30_Human',
        optionSetValue: false,
        color: '',
        warning: '',
    },
    lQYcD2hTocV: {
        required: false,
        hide: false,
        id: 'lQYcD2hTocV',
        valueType: 'NUMBER',
        displayFormName: 'Cefazolin_MIC_CLSI_Human',
        optionSetValue: false,
        color: '',
        warning: '',
    },
    AC3ZDhUyjDX: {
        required: false,
        hide: true,
        id: 'AC3ZDhUyjDX',
        valueType: 'TEXT',
        displayFormName: 'Cefazolin_Result',
        optionSetValue: true,
        optionSet: 'bSgpKbkbVGL',
    },
    tVIynZXmqls: {
        required: false,
        hide: false,
        id: 'tVIynZXmqls',
        valueType: 'NUMBER',
        displayFormName: 'Fosfomycin_Disk diffusion_CLSI_200_Human',
        optionSetValue: false,
        color: '',
        warning: '',
    },
    PTbpw8gED1N: {
        required: false,
        hide: false,
        id: 'PTbpw8gED1N',
        valueType: 'NUMBER',
        displayFormName: 'Fosfomycin_MIC_CLSI_Human',
        optionSetValue: false,
        color: '',
        warning: '',
    },
    mx4AYggTTir: {
        required: false,
        hide: true,
        id: 'mx4AYggTTir',
        valueType: 'TEXT',
        displayFormName: 'Fosfomycin_Result',
        optionSetValue: true,
        optionSet: 'bSgpKbkbVGL',
    },
    DGZI26b22go: {
        required: false,
        hide: false,
        id: 'DGZI26b22go',
        valueType: 'NUMBER',
        displayFormName: 'Colistin_MIC_EUCAST_Human',
        optionSetValue: false,
    },
    eGqo7EpSqhA: {
        required: false,
        hide: false,
        id: 'eGqo7EpSqhA',
        valueType: 'TEXT',
        displayFormName: 'AmpC',
        optionSetValue: true,
        optionSet: 'RyWAfSTIKae',
    },
    eYLIi9qzRgz: {
        required: false,
        hide: false,
        id: 'eYLIi9qzRgz',
        valueType: 'TEXT',
        displayFormName: 'Carba NP confirmatory test',
        optionSetValue: true,
        optionSet: 'RyWAfSTIKae',
    },
    oqziA8urxFq: {
        required: false,
        hide: false,
        id: 'oqziA8urxFq',
        valueType: 'TEXT',
        displayFormName: 'Carbapenemase - Imipenem - EDTA',
        optionSetValue: true,
        optionSet: 'RyWAfSTIKae',
    },
    qwtAhlVyVCM: {
        required: false,
        hide: false,
        id: 'qwtAhlVyVCM',
        valueType: 'TEXT',
        displayFormName: 'ESBL',
        optionSetValue: true,
        optionSet: 'RyWAfSTIKae',
    },
    n280itgv0pc: {
        required: false,
        hide: false,
        id: 'n280itgv0pc',
        valueType: 'TEXT',
        displayFormName: 'AmpC - ACC',
        optionSetValue: true,
        optionSet: 'RyWAfSTIKae',
    },
    el253B8KxIO: {
        required: false,
        hide: false,
        id: 'el253B8KxIO',
        valueType: 'TEXT',
        displayFormName: 'AmpC - CIT',
        optionSetValue: true,
        optionSet: 'RyWAfSTIKae',
    },
    ZMGTVgARAjB: {
        required: false,
        hide: false,
        id: 'ZMGTVgARAjB',
        valueType: 'TEXT',
        displayFormName: 'AmpC - DHA',
        optionSetValue: true,
        optionSet: 'RyWAfSTIKae',
    },
    DN2gTLIY37z: {
        required: false,
        hide: false,
        id: 'DN2gTLIY37z',
        valueType: 'TEXT',
        displayFormName: 'AmpC - EBC',
        optionSetValue: true,
        optionSet: 'RyWAfSTIKae',
    },
    H7pX1NhU9b2: {
        required: false,
        hide: false,
        id: 'H7pX1NhU9b2',
        valueType: 'TEXT',
        displayFormName: 'AmpC - MOX',
        optionSetValue: true,
        optionSet: 'RyWAfSTIKae',
    },
    KbzF1gX26kT: {
        required: false,
        hide: false,
        id: 'KbzF1gX26kT',
        valueType: 'TEXT',
        displayFormName: 'Carbapenemase - IMP',
        optionSetValue: true,
        optionSet: 'RyWAfSTIKae',
    },
    PIlH8Hbkm02: {
        required: false,
        hide: false,
        id: 'PIlH8Hbkm02',
        valueType: 'TEXT',
        displayFormName: 'Carbapenemase - KPC',
        optionSetValue: true,
        optionSet: 'RyWAfSTIKae',
    },
    zj5YX1v02Xd: {
        required: false,
        hide: false,
        id: 'zj5YX1v02Xd',
        valueType: 'TEXT',
        displayFormName: 'Carbapenemase - NDM - 1',
        optionSetValue: true,
        optionSet: 'RyWAfSTIKae',
    },
    PtRZ073XrxS: {
        required: false,
        hide: false,
        id: 'PtRZ073XrxS',
        valueType: 'TEXT',
        displayFormName: 'Carbapenemase - VIM',
        optionSetValue: true,
        optionSet: 'RyWAfSTIKae',
    },
    FPMhfReDAqt: {
        required: false,
        hide: false,
        id: 'FPMhfReDAqt',
        valueType: 'TEXT',
        displayFormName: 'ESBL - CTX - M - 1',
        optionSetValue: true,
        optionSet: 'RyWAfSTIKae',
    },
    TSVUS90Dvw6: {
        required: false,
        hide: false,
        id: 'TSVUS90Dvw6',
        valueType: 'TEXT',
        displayFormName: 'ESBL - CTX - M - 2',
        optionSetValue: true,
        optionSet: 'RyWAfSTIKae',
    },
    ezVuuGTMt4p: {
        required: false,
        hide: false,
        id: 'ezVuuGTMt4p',
        valueType: 'TEXT',
        displayFormName: 'ESBL - CTX - M - 8/25 ',
        optionSetValue: true,
        optionSet: 'RyWAfSTIKae',
    },
    tDskrlL66k3: {
        required: false,
        hide: false,
        id: 'tDskrlL66k3',
        valueType: 'TEXT',
        displayFormName: 'ESBL - CTX - M - 9',
        optionSetValue: true,
        optionSet: 'RyWAfSTIKae',
    },
    kHFQmnaSKZA: {
        required: false,
        hide: false,
        id: 'kHFQmnaSKZA',
        valueType: 'TEXT',
        displayFormName: ' ESBL - OXA - 1',
        optionSetValue: true,
        optionSet: 'RyWAfSTIKae',
    },
    QVUb8CY6OTX: {
        required: false,
        hide: false,
        id: 'QVUb8CY6OTX',
        valueType: 'TEXT',
        displayFormName: 'ESBL - PER',
        optionSetValue: true,
        optionSet: 'RyWAfSTIKae',
    },
    e6VZ8ga7uCi: {
        required: false,
        hide: false,
        id: 'e6VZ8ga7uCi',
        valueType: 'TEXT',
        displayFormName: 'ESBL - SHV',
        optionSetValue: true,
        optionSet: 'RyWAfSTIKae',
    },
    bfMusN9Jspz: {
        required: false,
        hide: false,
        id: 'bfMusN9Jspz',
        valueType: 'TEXT',
        displayFormName: 'ESBL - TEM',
        optionSetValue: true,
        optionSet: 'RyWAfSTIKae',
    },
    LKslj5qwCsY: {
        required: false,
        hide: false,
        id: 'LKslj5qwCsY',
        valueType: 'TEXT',
        displayFormName: 'ESBL - VEB',
        optionSetValue: true,
        optionSet: 'RyWAfSTIKae',
    },
    CrkSOhRJQbn: {
        required: false,
        hide: false,
        id: 'CrkSOhRJQbn',
        valueType: 'TEXT',
        displayFormName: 'Colistin_Result',
        optionSetValue: true,
        optionSet: 'bSgpKbkbVGL',
    },
    nVpNqeBuaHC: {
        required: false,
        hide: false,
        id: 'nVpNqeBuaHC',
        valueType: 'TEXT',
        displayFormName: 'Carbapenemase - Modified Hodge test',
        optionSetValue: true,
        optionSet: 'RyWAfSTIKae',
    },
    LA0aVW2YknF: {
        required: false,
        hide: false,
        id: 'LA0aVW2YknF',
        valueType: 'TEXT',
        displayFormName: 'AmpC - FOX',
        optionSetValue: true,
        optionSet: 'RyWAfSTIKae',
    },
    tAyVrNUTVHX: {
        required: false,
        hide: false,
        code: 'level_1_approval_status',
        id: 'tAyVrNUTVHX',
        valueType: 'TEXT',
        displayFormName: 'Level 1 Approval Status',
        optionSetValue: true,
        optionSet: 'evWmMLnWtvl',
    },
    wCNQtIHJRON: {
        required: false,
        hide: true,
        code: 'level_1_reason_for_record_revision',
        id: 'wCNQtIHJRON',
        valueType: 'TEXT',
        displayFormName: 'Level 1 Reason for record revision',
        optionSetValue: false,
    },
    NLmLwjdSHMv: {
        required: false,
        hide: true,
        code: 'level_1_reason_for_rejection',
        id: 'NLmLwjdSHMv',
        valueType: 'TEXT',
        displayFormName: 'Level 1 Reason For Rejection',
        optionSetValue: false,
    },
    sXDQT6Yaf77: {
        required: false,
        hide: false,
        code: 'level_2_approval_status',
        id: 'sXDQT6Yaf77',
        valueType: 'TEXT',
        displayFormName: 'Level 2 Approval Status',
        optionSetValue: true,
        optionSet: 'evWmMLnWtvl',
    },
    fEnFVvEFKVc: {
        required: false,
        hide: true,
        code: 'level_2_reason_for_record_revision',
        id: 'fEnFVvEFKVc',
        valueType: 'TEXT',
        displayFormName: 'Level 2 Reason for record revision',
        optionSetValue: false,
    },
    pz8SoHBO6RL: {
        required: false,
        hide: true,
        code: 'level_2_reason_for_rejection',
        id: 'pz8SoHBO6RL',
        valueType: 'TEXT',
        displayFormName: 'Level 2 Reason For Rejection',
        optionSetValue: false,
    },
    L6ZyBJGOeAV: { required: false, hide: false },
    wNTllPkgB92: {
        required: false,
        hide: false,
        code: 'IT - Batch number',
        id: 'wNTllPkgB92',
        valueType: 'TEXT',
        displayFormName: 'IT - Batch number',
        optionSetValue: false,
    },
    nU2wf4hwlDD: {
        required: false,
        hide: false,
        code: 'IT - Dispatch date',
        id: 'nU2wf4hwlDD',
        valueType: 'DATE',
        displayFormName: 'IT - Dispatch date',
        optionSetValue: false,
    },
    D4jwjr4opAv: {
        required: false,
        hide: false,
        code: 'IT - Dispatch status',
        id: 'D4jwjr4opAv',
        valueType: 'TEXT',
        displayFormName: 'IT - Dispatch status',
        optionSetValue: true,
        optionSet: 'zqJkxfnDRAd',
    },
    H4s7FuoY3Hm: {
        required: false,
        hide: false,
        code: 'IT - Isolate condition',
        id: 'H4s7FuoY3Hm',
        valueType: 'TEXT',
        displayFormName: 'Condition',
        optionSetValue: true,
        optionSet: 'WaVwSkK76zO',
    },
    KHHHMoiUsWZ: {
        required: false,
        hide: false,
        code: 'IT - Isolate status',
        id: 'KHHHMoiUsWZ',
        valueType: 'TEXT',
        displayFormName: 'Status',
        optionSetValue: true,
        optionSet: 'OeZFu9N3ihh',
    },
    qNmtxrjYccb: {
        required: false,
        hide: false,
        code: 'IT - Molecular test date',
        id: 'qNmtxrjYccb',
        valueType: 'DATE',
        displayFormName: 'Molecular test',
        optionSetValue: false,
    },
    hQmS69HXStI: {
        required: false,
        hide: false,
        code: 'IT - Quality check date',
        id: 'hQmS69HXStI',
        valueType: 'DATE',
        displayFormName: 'Quality check',
        optionSetValue: false,
    },
    BQwb1YbN3mH: {
        required: false,
        hide: false,
        code: 'IT - Received date',
        id: 'BQwb1YbN3mH',
        valueType: 'DATE',
        displayFormName: 'IT - Received date',
        optionSetValue: false,
    },
    ZPEtHK3dlXf: { required: false, hide: false },
    nP6QJxLhB2o: { required: false, hide: false },
}
